/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\HJJ\\Desktop\\Blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-50e0f714",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50e0f714").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-18d957c6",
    path: "/note/CSS/css%20%E5%AE%9E%E7%8E%B0%E4%B8%8A%E5%8F%B3%E4%B8%8B%E5%B7%A6%E4%B8%89%E8%A7%92.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18d957c6").then(next)
    },
  },
  {
    path: "/note/CSS/css 实现上右下左三角.html",
    redirect: "/note/CSS/css%20%E5%AE%9E%E7%8E%B0%E4%B8%8A%E5%8F%B3%E4%B8%8B%E5%B7%A6%E4%B8%89%E8%A7%92.html"
  },
  {
    path: "/note/CSS/css 实现上右下左三角.html",
    redirect: "/note/CSS/css%20%E5%AE%9E%E7%8E%B0%E4%B8%8A%E5%8F%B3%E4%B8%8B%E5%B7%A6%E4%B8%89%E8%A7%92.html"
  },
  {
    name: "v-61c357fb",
    path: "/note/CSS/mixin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61c357fb").then(next)
    },
  },
  {
    name: "v-4c24a392",
    path: "/note/CSS/DIV%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4c24a392").then(next)
    },
  },
  {
    path: "/note/CSS/DIV水平垂直居中.html",
    redirect: "/note/CSS/DIV%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD.html"
  },
  {
    path: "/note/CSS/DIV水平垂直居中.html",
    redirect: "/note/CSS/DIV%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD.html"
  },
  {
    name: "v-896af054",
    path: "/note/CSS/retina%E5%B1%8F%E5%B9%951px%E8%BE%B9%E6%A1%86%E9%97%AE%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-896af054").then(next)
    },
  },
  {
    path: "/note/CSS/retina屏幕1px边框问题.html",
    redirect: "/note/CSS/retina%E5%B1%8F%E5%B9%951px%E8%BE%B9%E6%A1%86%E9%97%AE%E9%A2%98.html"
  },
  {
    path: "/note/CSS/retina屏幕1px边框问题.html",
    redirect: "/note/CSS/retina%E5%B1%8F%E5%B9%951px%E8%BE%B9%E6%A1%86%E9%97%AE%E9%A2%98.html"
  },
  {
    name: "v-4bd53062",
    path: "/note/CSS/%E5%A4%A7%E5%B1%8F%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4bd53062").then(next)
    },
  },
  {
    path: "/note/CSS/大屏适配方案.html",
    redirect: "/note/CSS/%E5%A4%A7%E5%B1%8F%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html"
  },
  {
    path: "/note/CSS/大屏适配方案.html",
    redirect: "/note/CSS/%E5%A4%A7%E5%B1%8F%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html"
  },
  {
    name: "v-39e44bdf",
    path: "/note/CSS/sass.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39e44bdf").then(next)
    },
  },
  {
    name: "v-4173ef9e",
    path: "/note/CSS/CSS%E9%AB%98%E7%BA%A7%E5%B8%B8%E8%A7%81%E6%8A%80%E5%B7%A7%E6%B1%87%E6%80%BB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4173ef9e").then(next)
    },
  },
  {
    path: "/note/CSS/CSS高级常见技巧汇总.html",
    redirect: "/note/CSS/CSS%E9%AB%98%E7%BA%A7%E5%B8%B8%E8%A7%81%E6%8A%80%E5%B7%A7%E6%B1%87%E6%80%BB.html"
  },
  {
    path: "/note/CSS/CSS高级常见技巧汇总.html",
    redirect: "/note/CSS/CSS%E9%AB%98%E7%BA%A7%E5%B8%B8%E8%A7%81%E6%8A%80%E5%B7%A7%E6%B1%87%E6%80%BB.html"
  },
  {
    name: "v-2d6dd408",
    path: "/note/CSS/%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E7%9A%84%E5%BC%95%E7%94%A8%E5%92%8C%E5%8E%8B%E7%BC%A9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d6dd408").then(next)
    },
  },
  {
    path: "/note/CSS/字体文件的引用和压缩.html",
    redirect: "/note/CSS/%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E7%9A%84%E5%BC%95%E7%94%A8%E5%92%8C%E5%8E%8B%E7%BC%A9.html"
  },
  {
    path: "/note/CSS/字体文件的引用和压缩.html",
    redirect: "/note/CSS/%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E7%9A%84%E5%BC%95%E7%94%A8%E5%92%8C%E5%8E%8B%E7%BC%A9.html"
  },
  {
    name: "v-7257daa5",
    path: "/note/CSS/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7257daa5").then(next)
    },
  },
  {
    path: "/note/CSS/移动端适配方案.html",
    redirect: "/note/CSS/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html"
  },
  {
    path: "/note/CSS/移动端适配方案.html",
    redirect: "/note/CSS/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html"
  },
  {
    name: "v-5a7b5e90",
    path: "/note/CSS/%E6%B8%90%E5%8F%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a7b5e90").then(next)
    },
  },
  {
    path: "/note/CSS/渐变.html",
    redirect: "/note/CSS/%E6%B8%90%E5%8F%98.html"
  },
  {
    path: "/note/CSS/渐变.html",
    redirect: "/note/CSS/%E6%B8%90%E5%8F%98.html"
  },
  {
    name: "v-140730de",
    path: "/note/HTML/audio%E6%A0%87%E7%AD%BE%E5%B8%B8%E7%94%A8api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-140730de").then(next)
    },
  },
  {
    path: "/note/HTML/audio标签常用api.html",
    redirect: "/note/HTML/audio%E6%A0%87%E7%AD%BE%E5%B8%B8%E7%94%A8api.html"
  },
  {
    path: "/note/HTML/audio标签常用api.html",
    redirect: "/note/HTML/audio%E6%A0%87%E7%AD%BE%E5%B8%B8%E7%94%A8api.html"
  },
  {
    name: "v-daeef31a",
    path: "/note/HTML/canvas.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-daeef31a").then(next)
    },
  },
  {
    name: "v-5ac3a38d",
    path: "/note/CSS/%E9%9A%90%E8%97%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%88%96%E6%9B%B4%E6%94%B9%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%A0%B7%E5%BC%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ac3a38d").then(next)
    },
  },
  {
    path: "/note/CSS/隐藏滚动条或更改滚动条样式.html",
    redirect: "/note/CSS/%E9%9A%90%E8%97%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%88%96%E6%9B%B4%E6%94%B9%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%A0%B7%E5%BC%8F.html"
  },
  {
    path: "/note/CSS/隐藏滚动条或更改滚动条样式.html",
    redirect: "/note/CSS/%E9%9A%90%E8%97%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%88%96%E6%9B%B4%E6%94%B9%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%A0%B7%E5%BC%8F.html"
  },
  {
    name: "v-057a5a9c",
    path: "/note/HTML/dpr%E3%80%81%E8%AE%BE%E5%A4%87%E5%83%8F%E7%B4%A0%E3%80%81CSS%E5%83%8F%E7%B4%A0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-057a5a9c").then(next)
    },
  },
  {
    path: "/note/HTML/dpr、设备像素、CSS像素.html",
    redirect: "/note/HTML/dpr%E3%80%81%E8%AE%BE%E5%A4%87%E5%83%8F%E7%B4%A0%E3%80%81CSS%E5%83%8F%E7%B4%A0.html"
  },
  {
    path: "/note/HTML/dpr、设备像素、CSS像素.html",
    redirect: "/note/HTML/dpr%E3%80%81%E8%AE%BE%E5%A4%87%E5%83%8F%E7%B4%A0%E3%80%81CSS%E5%83%8F%E7%B4%A0.html"
  },
  {
    name: "v-1e565195",
    path: "/note/HTML/h5%E6%96%B0%E7%89%B9%E6%80%A7.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e565195").then(next)
    },
  },
  {
    path: "/note/HTML/h5新特性.html",
    redirect: "/note/HTML/h5%E6%96%B0%E7%89%B9%E6%80%A7.html"
  },
  {
    path: "/note/HTML/h5新特性.html",
    redirect: "/note/HTML/h5%E6%96%B0%E7%89%B9%E6%80%A7.html"
  },
  {
    name: "v-32967ca5",
    path: "/note/HTML/input.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32967ca5").then(next)
    },
  },
  {
    name: "v-3cdbaef4",
    path: "/note/HTML/h5%E8%AF%AD%E4%B9%89%E5%8C%96%E6%A0%87%E7%AD%BE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3cdbaef4").then(next)
    },
  },
  {
    path: "/note/HTML/h5语义化标签.html",
    redirect: "/note/HTML/h5%E8%AF%AD%E4%B9%89%E5%8C%96%E6%A0%87%E7%AD%BE.html"
  },
  {
    path: "/note/HTML/h5语义化标签.html",
    redirect: "/note/HTML/h5%E8%AF%AD%E4%B9%89%E5%8C%96%E6%A0%87%E7%AD%BE.html"
  },
  {
    name: "v-549cc44e",
    path: "/note/HTML/meta.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-549cc44e").then(next)
    },
  },
  {
    name: "v-22dbdfb6",
    path: "/note/HTML/%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E5%88%A9%E7%94%A8%E5%A4%9A%E4%B8%AA%E5%9F%9F%E5%90%8D%E6%9D%A5%E5%AD%98%E5%82%A8%E7%BD%91%E7%AB%99%E8%B5%84%E6%BA%90%E6%9B%B4%E6%9C%89%E6%95%88%EF%BC%9F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-22dbdfb6").then(next)
    },
  },
  {
    path: "/note/HTML/为什么会利用多个域名来存储网站资源更有效？.html",
    redirect: "/note/HTML/%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E5%88%A9%E7%94%A8%E5%A4%9A%E4%B8%AA%E5%9F%9F%E5%90%8D%E6%9D%A5%E5%AD%98%E5%82%A8%E7%BD%91%E7%AB%99%E8%B5%84%E6%BA%90%E6%9B%B4%E6%9C%89%E6%95%88%EF%BC%9F.html"
  },
  {
    path: "/note/HTML/为什么会利用多个域名来存储网站资源更有效？.html",
    redirect: "/note/HTML/%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E5%88%A9%E7%94%A8%E5%A4%9A%E4%B8%AA%E5%9F%9F%E5%90%8D%E6%9D%A5%E5%AD%98%E5%82%A8%E7%BD%91%E7%AB%99%E8%B5%84%E6%BA%90%E6%9B%B4%E6%9C%89%E6%95%88%EF%BC%9F.html"
  },
  {
    name: "v-fbb1ff76",
    path: "/note/HTML/video.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fbb1ff76").then(next)
    },
  },
  {
    name: "v-61c0020b",
    path: "/note/HTML/%E5%85%B6%E4%BB%96%E7%AE%80%E7%AD%94%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61c0020b").then(next)
    },
  },
  {
    path: "/note/HTML/其他简答题.html",
    redirect: "/note/HTML/%E5%85%B6%E4%BB%96%E7%AE%80%E7%AD%94%E9%A2%98.html"
  },
  {
    path: "/note/HTML/其他简答题.html",
    redirect: "/note/HTML/%E5%85%B6%E4%BB%96%E7%AE%80%E7%AD%94%E9%A2%98.html"
  },
  {
    name: "v-075cb6cd",
    path: "/note/HTML/script.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-075cb6cd").then(next)
    },
  },
  {
    name: "v-435a9109",
    path: "/note/HTML/%E5%89%8D%E7%AB%AF%E9%9C%80%E8%A6%81%E6%B3%A8%E6%84%8F%E5%93%AA%E4%BA%9BSEO.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-435a9109").then(next)
    },
  },
  {
    path: "/note/HTML/前端需要注意哪些SEO.html",
    redirect: "/note/HTML/%E5%89%8D%E7%AB%AF%E9%9C%80%E8%A6%81%E6%B3%A8%E6%84%8F%E5%93%AA%E4%BA%9BSEO.html"
  },
  {
    path: "/note/HTML/前端需要注意哪些SEO.html",
    redirect: "/note/HTML/%E5%89%8D%E7%AB%AF%E9%9C%80%E8%A6%81%E6%B3%A8%E6%84%8F%E5%93%AA%E4%BA%9BSEO.html"
  },
  {
    name: "v-4bc1ce98",
    path: "/note/HTML/%E5%9B%BE%E7%89%87.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4bc1ce98").then(next)
    },
  },
  {
    path: "/note/HTML/图片.html",
    redirect: "/note/HTML/%E5%9B%BE%E7%89%87.html"
  },
  {
    path: "/note/HTML/图片.html",
    redirect: "/note/HTML/%E5%9B%BE%E7%89%87.html"
  },
  {
    name: "v-27b2f202",
    path: "/note/JavaScript/call()%E3%80%81apply()%E3%80%81bind().html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27b2f202").then(next)
    },
  },
  {
    path: "/note/JavaScript/call()、apply()、bind().html",
    redirect: "/note/JavaScript/call()%E3%80%81apply()%E3%80%81bind().html"
  },
  {
    path: "/note/JavaScript/call()、apply()、bind().html",
    redirect: "/note/JavaScript/call()%E3%80%81apply()%E3%80%81bind().html"
  },
  {
    name: "v-5c4a2edf",
    path: "/note/HTML/%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0%E6%B5%8F%E8%A7%88%E5%99%A8%E5%86%85%E5%A4%9A%E4%B8%AA%E6%A0%87%E7%AD%BE%E4%B9%9F%E4%B9%8B%E9%97%B4%E7%9A%84%E9%80%9A%E4%BF%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c4a2edf").then(next)
    },
  },
  {
    path: "/note/HTML/如何实现浏览器内多个标签也之间的通信.html",
    redirect: "/note/HTML/%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0%E6%B5%8F%E8%A7%88%E5%99%A8%E5%86%85%E5%A4%9A%E4%B8%AA%E6%A0%87%E7%AD%BE%E4%B9%9F%E4%B9%8B%E9%97%B4%E7%9A%84%E9%80%9A%E4%BF%A1.html"
  },
  {
    path: "/note/HTML/如何实现浏览器内多个标签也之间的通信.html",
    redirect: "/note/HTML/%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0%E6%B5%8F%E8%A7%88%E5%99%A8%E5%86%85%E5%A4%9A%E4%B8%AA%E6%A0%87%E7%AD%BE%E4%B9%9F%E4%B9%8B%E9%97%B4%E7%9A%84%E9%80%9A%E4%BF%A1.html"
  },
  {
    name: "v-32c96274",
    path: "/note/JavaScript/JS%E4%B8%AD%E7%9A%84offsetWidth%E3%80%81offsetHeight%E3%80%81clientWidth%E3%80%81clientHeight%E7%AD%89%E7%AD%89%E7%9A%84%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32c96274").then(next)
    },
  },
  {
    path: "/note/JavaScript/JS中的offsetWidth、offsetHeight、clientWidth、clientHeight等等的详细介绍.html",
    redirect: "/note/JavaScript/JS%E4%B8%AD%E7%9A%84offsetWidth%E3%80%81offsetHeight%E3%80%81clientWidth%E3%80%81clientHeight%E7%AD%89%E7%AD%89%E7%9A%84%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.html"
  },
  {
    path: "/note/JavaScript/JS中的offsetWidth、offsetHeight、clientWidth、clientHeight等等的详细介绍.html",
    redirect: "/note/JavaScript/JS%E4%B8%AD%E7%9A%84offsetWidth%E3%80%81offsetHeight%E3%80%81clientWidth%E3%80%81clientHeight%E7%AD%89%E7%AD%89%E7%9A%84%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.html"
  },
  {
    name: "v-a58dcba6",
    path: "/note/JavaScript/js%E5%86%85%E7%BD%AE%E5%AF%B9%E8%B1%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a58dcba6").then(next)
    },
  },
  {
    path: "/note/JavaScript/js内置对象.html",
    redirect: "/note/JavaScript/js%E5%86%85%E7%BD%AE%E5%AF%B9%E8%B1%A1.html"
  },
  {
    path: "/note/JavaScript/js内置对象.html",
    redirect: "/note/JavaScript/js%E5%86%85%E7%BD%AE%E5%AF%B9%E8%B1%A1.html"
  },
  {
    name: "v-9925e42e",
    path: "/note/JavaScript/jquery%E5%B0%8F%E7%AC%94%E8%AE%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9925e42e").then(next)
    },
  },
  {
    path: "/note/JavaScript/jquery小笔记.html",
    redirect: "/note/JavaScript/jquery%E5%B0%8F%E7%AC%94%E8%AE%B0.html"
  },
  {
    path: "/note/JavaScript/jquery小笔记.html",
    redirect: "/note/JavaScript/jquery%E5%B0%8F%E7%AC%94%E8%AE%B0.html"
  },
  {
    name: "v-e313921c",
    path: "/note/JavaScript/js%E5%87%BD%E6%95%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e313921c").then(next)
    },
  },
  {
    path: "/note/JavaScript/js函数.html",
    redirect: "/note/JavaScript/js%E5%87%BD%E6%95%B0.html"
  },
  {
    path: "/note/JavaScript/js函数.html",
    redirect: "/note/JavaScript/js%E5%87%BD%E6%95%B0.html"
  },
  {
    name: "v-c74fcb98",
    path: "/note/JavaScript/js%E5%AD%97%E7%AC%A6%E4%B8%B2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c74fcb98").then(next)
    },
  },
  {
    path: "/note/JavaScript/js字符串.html",
    redirect: "/note/JavaScript/js%E5%AD%97%E7%AC%A6%E4%B8%B2.html"
  },
  {
    path: "/note/JavaScript/js字符串.html",
    redirect: "/note/JavaScript/js%E5%AD%97%E7%AC%A6%E4%B8%B2.html"
  },
  {
    name: "v-35a4858b",
    path: "/note/JavaScript/js%E5%8E%9F%E5%9E%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35a4858b").then(next)
    },
  },
  {
    path: "/note/JavaScript/js原型.html",
    redirect: "/note/JavaScript/js%E5%8E%9F%E5%9E%8B.html"
  },
  {
    path: "/note/JavaScript/js原型.html",
    redirect: "/note/JavaScript/js%E5%8E%9F%E5%9E%8B.html"
  },
  {
    name: "v-00e2c9cd",
    path: "/note/JavaScript/js%E6%89%A7%E8%A1%8C%E8%BF%87%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00e2c9cd").then(next)
    },
  },
  {
    path: "/note/JavaScript/js执行过程.html",
    redirect: "/note/JavaScript/js%E6%89%A7%E8%A1%8C%E8%BF%87%E7%A8%8B.html"
  },
  {
    path: "/note/JavaScript/js执行过程.html",
    redirect: "/note/JavaScript/js%E6%89%A7%E8%A1%8C%E8%BF%87%E7%A8%8B.html"
  },
  {
    name: "v-5e1b87bb",
    path: "/note/CSS/%E8%AE%BE%E7%BD%AEinput.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e1b87bb").then(next)
    },
  },
  {
    path: "/note/CSS/设置input.html",
    redirect: "/note/CSS/%E8%AE%BE%E7%BD%AEinput.html"
  },
  {
    path: "/note/CSS/设置input.html",
    redirect: "/note/CSS/%E8%AE%BE%E7%BD%AEinput.html"
  },
  {
    name: "v-54cbd2b6",
    path: "/note/JavaScript/js%E6%95%B0%E7%BB%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54cbd2b6").then(next)
    },
  },
  {
    path: "/note/JavaScript/js数组.html",
    redirect: "/note/JavaScript/js%E6%95%B0%E7%BB%84.html"
  },
  {
    path: "/note/JavaScript/js数组.html",
    redirect: "/note/JavaScript/js%E6%95%B0%E7%BB%84.html"
  },
  {
    name: "v-7caad962",
    path: "/note/JavaScript/js%E6%AD%A3%E5%88%99.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7caad962").then(next)
    },
  },
  {
    path: "/note/JavaScript/js正则.html",
    redirect: "/note/JavaScript/js%E6%AD%A3%E5%88%99.html"
  },
  {
    path: "/note/JavaScript/js正则.html",
    redirect: "/note/JavaScript/js%E6%AD%A3%E5%88%99.html"
  },
  {
    name: "v-75884935",
    path: "/note/JavaScript/js%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75884935").then(next)
    },
  },
  {
    path: "/note/JavaScript/js面向对象.html",
    redirect: "/note/JavaScript/js%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html"
  },
  {
    path: "/note/JavaScript/js面向对象.html",
    redirect: "/note/JavaScript/js%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html"
  },
  {
    name: "v-1c4e1118",
    path: "/note/JavaScript/js%E9%97%AD%E5%8C%85.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c4e1118").then(next)
    },
  },
  {
    path: "/note/JavaScript/js闭包.html",
    redirect: "/note/JavaScript/js%E9%97%AD%E5%8C%85.html"
  },
  {
    path: "/note/JavaScript/js闭包.html",
    redirect: "/note/JavaScript/js%E9%97%AD%E5%8C%85.html"
  },
  {
    name: "v-232abf48",
    path: "/note/JavaScript/js%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-232abf48").then(next)
    },
  },
  {
    path: "/note/JavaScript/js数据类型2.html",
    redirect: "/note/JavaScript/js%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B2.html"
  },
  {
    path: "/note/JavaScript/js数据类型2.html",
    redirect: "/note/JavaScript/js%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B2.html"
  },
  {
    name: "v-bd5ec76c",
    path: "/note/JavaScript/%E5%86%85%E5%AD%98%E6%B3%84%E6%BC%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bd5ec76c").then(next)
    },
  },
  {
    path: "/note/JavaScript/内存泄漏.html",
    redirect: "/note/JavaScript/%E5%86%85%E5%AD%98%E6%B3%84%E6%BC%8F.html"
  },
  {
    path: "/note/JavaScript/内存泄漏.html",
    redirect: "/note/JavaScript/%E5%86%85%E5%AD%98%E6%B3%84%E6%BC%8F.html"
  },
  {
    name: "v-21e534be",
    path: "/note/JavaScript/%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6%E6%9C%BA%E5%88%B6GC.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21e534be").then(next)
    },
  },
  {
    path: "/note/JavaScript/垃圾回收机制GC.html",
    redirect: "/note/JavaScript/%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6%E6%9C%BA%E5%88%B6GC.html"
  },
  {
    path: "/note/JavaScript/垃圾回收机制GC.html",
    redirect: "/note/JavaScript/%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6%E6%9C%BA%E5%88%B6GC.html"
  },
  {
    name: "v-3c54c848",
    path: "/note/JavaScript/%E6%95%B0%E7%BB%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c54c848").then(next)
    },
  },
  {
    path: "/note/JavaScript/数组.html",
    redirect: "/note/JavaScript/%E6%95%B0%E7%BB%84.html"
  },
  {
    path: "/note/JavaScript/数组.html",
    redirect: "/note/JavaScript/%E6%95%B0%E7%BB%84.html"
  },
  {
    name: "v-19bbd990",
    path: "/note/JavaScript/js%E8%AF%AD%E5%8F%A5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19bbd990").then(next)
    },
  },
  {
    path: "/note/JavaScript/js语句.html",
    redirect: "/note/JavaScript/js%E8%AF%AD%E5%8F%A5.html"
  },
  {
    path: "/note/JavaScript/js语句.html",
    redirect: "/note/JavaScript/js%E8%AF%AD%E5%8F%A5.html"
  },
  {
    name: "v-09689aec",
    path: "/note/JavaScript/%E5%BF%AB%E9%80%9F%E6%8E%92%E5%BA%8F%E7%AE%97%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09689aec").then(next)
    },
  },
  {
    path: "/note/JavaScript/快速排序算法.html",
    redirect: "/note/JavaScript/%E5%BF%AB%E9%80%9F%E6%8E%92%E5%BA%8F%E7%AE%97%E6%B3%95.html"
  },
  {
    path: "/note/JavaScript/快速排序算法.html",
    redirect: "/note/JavaScript/%E5%BF%AB%E9%80%9F%E6%8E%92%E5%BA%8F%E7%AE%97%E6%B3%95.html"
  },
  {
    name: "v-b16f5d54",
    path: "/note/JavaScript/js%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b16f5d54").then(next)
    },
  },
  {
    path: "/note/JavaScript/js数据类型.html",
    redirect: "/note/JavaScript/js%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B.html"
  },
  {
    path: "/note/JavaScript/js数据类型.html",
    redirect: "/note/JavaScript/js%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B.html"
  },
  {
    name: "v-3b8007b2",
    path: "/note/JavaScript/%E6%B7%B1%E6%8B%B7%E8%B4%9D%E5%92%8C%E6%B5%85%E6%8B%B7%E8%B4%9D.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b8007b2").then(next)
    },
  },
  {
    path: "/note/JavaScript/深拷贝和浅拷贝.html",
    redirect: "/note/JavaScript/%E6%B7%B1%E6%8B%B7%E8%B4%9D%E5%92%8C%E6%B5%85%E6%8B%B7%E8%B4%9D.html"
  },
  {
    path: "/note/JavaScript/深拷贝和浅拷贝.html",
    redirect: "/note/JavaScript/%E6%B7%B1%E6%8B%B7%E8%B4%9D%E5%92%8C%E6%B5%85%E6%8B%B7%E8%B4%9D.html"
  },
  {
    name: "v-5bbaf890",
    path: "/note/JavaScript/%E8%A7%A3%E5%86%B3JavaScript%E6%95%B0%E5%AD%97%E7%B2%BE%E5%BA%A6%E4%B8%A2%E5%A4%B1%E9%97%AE%E9%A2%98%E7%9A%84%E6%96%B9%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5bbaf890").then(next)
    },
  },
  {
    path: "/note/JavaScript/解决JavaScript数字精度丢失问题的方法.html",
    redirect: "/note/JavaScript/%E8%A7%A3%E5%86%B3JavaScript%E6%95%B0%E5%AD%97%E7%B2%BE%E5%BA%A6%E4%B8%A2%E5%A4%B1%E9%97%AE%E9%A2%98%E7%9A%84%E6%96%B9%E6%B3%95.html"
  },
  {
    path: "/note/JavaScript/解决JavaScript数字精度丢失问题的方法.html",
    redirect: "/note/JavaScript/%E8%A7%A3%E5%86%B3JavaScript%E6%95%B0%E5%AD%97%E7%B2%BE%E5%BA%A6%E4%B8%A2%E5%A4%B1%E9%97%AE%E9%A2%98%E7%9A%84%E6%96%B9%E6%B3%95.html"
  },
  {
    name: "v-06c183ed",
    path: "/note/JavaScript/%E7%BC%96%E7%A8%8B%E7%AE%97%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06c183ed").then(next)
    },
  },
  {
    path: "/note/JavaScript/编程算法.html",
    redirect: "/note/JavaScript/%E7%BC%96%E7%A8%8B%E7%AE%97%E6%B3%95.html"
  },
  {
    path: "/note/JavaScript/编程算法.html",
    redirect: "/note/JavaScript/%E7%BC%96%E7%A8%8B%E7%AE%97%E6%B3%95.html"
  },
  {
    name: "v-2c49a5e3",
    path: "/note/JavaScript/%E8%B7%A8%E5%9F%9F%E9%97%AE%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c49a5e3").then(next)
    },
  },
  {
    path: "/note/JavaScript/跨域问题.html",
    redirect: "/note/JavaScript/%E8%B7%A8%E5%9F%9F%E9%97%AE%E9%A2%98.html"
  },
  {
    path: "/note/JavaScript/跨域问题.html",
    redirect: "/note/JavaScript/%E8%B7%A8%E5%9F%9F%E9%97%AE%E9%A2%98.html"
  },
  {
    name: "v-18568991",
    path: "/note/JavaScript/%E9%98%B2%E6%8A%96%E8%8A%82%E6%B5%81.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18568991").then(next)
    },
  },
  {
    path: "/note/JavaScript/防抖节流.html",
    redirect: "/note/JavaScript/%E9%98%B2%E6%8A%96%E8%8A%82%E6%B5%81.html"
  },
  {
    path: "/note/JavaScript/防抖节流.html",
    redirect: "/note/JavaScript/%E9%98%B2%E6%8A%96%E8%8A%82%E6%B5%81.html"
  },
  {
    name: "v-bae62ae6",
    path: "/note/VuePress/vuepress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bae62ae6").then(next)
    },
  },
  {
    name: "v-9b6ec534",
    path: "/note/bi%E5%A4%A7%E5%B1%8F%E5%88%B6%E4%BD%9C/%E5%A4%A7%E5%B1%8F%E9%A1%B9%E7%9B%AE%E5%88%B6%E4%BD%9C%E7%AC%94%E8%AE%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9b6ec534").then(next)
    },
  },
  {
    path: "/note/bi大屏制作/大屏项目制作笔记.html",
    redirect: "/note/bi%E5%A4%A7%E5%B1%8F%E5%88%B6%E4%BD%9C/%E5%A4%A7%E5%B1%8F%E9%A1%B9%E7%9B%AE%E5%88%B6%E4%BD%9C%E7%AC%94%E8%AE%B0.html"
  },
  {
    path: "/note/bi大屏制作/大屏项目制作笔记.html",
    redirect: "/note/bi%E5%A4%A7%E5%B1%8F%E5%88%B6%E4%BD%9C/%E5%A4%A7%E5%B1%8F%E9%A1%B9%E7%9B%AE%E5%88%B6%E4%BD%9C%E7%AC%94%E8%AE%B0.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-3259a754",
    path: "/tag/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3259a754").then(next)
    },
    meta: {"pid":"tags","id":"CSS"}
  },
  {
    path: "/tag/CSS/index.html",
    redirect: "/tag/CSS/"
  },
  {
    name: "v-184d950c",
    path: "/tag/HTML/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-184d950c").then(next)
    },
    meta: {"pid":"tags","id":"HTML"}
  },
  {
    path: "/tag/HTML/index.html",
    redirect: "/tag/HTML/"
  },
  {
    name: "v-f1650aa2",
    path: "/tag/HTML5/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-f1650aa2").then(next)
    },
    meta: {"pid":"tags","id":"HTML5"}
  },
  {
    path: "/tag/HTML5/index.html",
    redirect: "/tag/HTML5/"
  },
  {
    name: "v-7a5f6990",
    path: "/tag/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7a5f6990").then(next)
    },
    meta: {"pid":"tags","id":"JavaScript"}
  },
  {
    path: "/tag/JavaScript/index.html",
    redirect: "/tag/JavaScript/"
  },
  {
    name: "v-dfb71430",
    path: "/tag/vuepress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-dfb71430").then(next)
    },
    meta: {"pid":"tags","id":"vuepress"}
  },
  {
    path: "/tag/vuepress/index.html",
    redirect: "/tag/vuepress/"
  },
  {
    name: "v-7efe64ca",
    path: "/categories/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7efe64ca").then(next)
    },
    meta: {"pid":"categories","id":"CSS"}
  },
  {
    path: "/categories/CSS/index.html",
    redirect: "/categories/CSS/"
  },
  {
    name: "v-61150b86",
    path: "/categories/HTML/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-61150b86").then(next)
    },
    meta: {"pid":"categories","id":"HTML"}
  },
  {
    path: "/categories/HTML/index.html",
    redirect: "/categories/HTML/"
  },
  {
    name: "v-081e6844",
    path: "/categories/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-081e6844").then(next)
    },
    meta: {"pid":"categories","id":"JavaScript"}
  },
  {
    path: "/categories/JavaScript/index.html",
    redirect: "/categories/JavaScript/"
  },
  {
    name: "v-9fa33418",
    path: "/categories/vuepress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-9fa33418").then(next)
    },
    meta: {"pid":"categories","id":"vuepress"}
  },
  {
    path: "/categories/vuepress/index.html",
    redirect: "/categories/vuepress/"
  },
  {
    name: "v-817b06b2",
    path: "/tag/CSS/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-817b06b2").then(next)
    },
    meta: {"pid":"tags","id":"CSS"}
  },
  {
    path: "/tag/CSS/page/2/index.html",
    redirect: "/tag/CSS/page/2/"
  },
  {
    name: "v-b48ab9fa",
    path: "/tag/HTML/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b48ab9fa").then(next)
    },
    meta: {"pid":"tags","id":"HTML"}
  },
  {
    path: "/tag/HTML/page/2/index.html",
    redirect: "/tag/HTML/page/2/"
  },
  {
    name: "v-169d88f6",
    path: "/tag/JavaScript/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-169d88f6").then(next)
    },
    meta: {"pid":"tags","id":"JavaScript"}
  },
  {
    path: "/tag/JavaScript/page/2/index.html",
    redirect: "/tag/JavaScript/page/2/"
  },
  {
    name: "v-169d88b8",
    path: "/tag/JavaScript/page/3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-169d88b8").then(next)
    },
    meta: {"pid":"tags","id":"JavaScript"}
  },
  {
    path: "/tag/JavaScript/page/3/index.html",
    redirect: "/tag/JavaScript/page/3/"
  },
  {
    name: "v-049099b3",
    path: "/categories/CSS/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-049099b3").then(next)
    },
    meta: {"pid":"categories","id":"CSS"}
  },
  {
    path: "/categories/CSS/page/2/index.html",
    redirect: "/categories/CSS/page/2/"
  },
  {
    name: "v-0a302777",
    path: "/categories/HTML/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a302777").then(next)
    },
    meta: {"pid":"categories","id":"HTML"}
  },
  {
    path: "/categories/HTML/page/2/index.html",
    redirect: "/categories/HTML/page/2/"
  },
  {
    name: "v-1c4698f9",
    path: "/categories/JavaScript/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c4698f9").then(next)
    },
    meta: {"pid":"categories","id":"JavaScript"}
  },
  {
    path: "/categories/JavaScript/page/2/index.html",
    redirect: "/categories/JavaScript/page/2/"
  },
  {
    name: "v-1c469918",
    path: "/categories/JavaScript/page/3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c469918").then(next)
    },
    meta: {"pid":"categories","id":"JavaScript"}
  },
  {
    path: "/categories/JavaScript/page/3/index.html",
    redirect: "/categories/JavaScript/page/3/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]