/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "HHH",
  "description": "菜菜又是想变成大佬的一天",
  "base": "/blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/blog/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "HJJ"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "一个小小前端的学习笔记!"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/blog/manifest.json"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/blog/icons/apple-touch-icon.png"
      }
    ],
    [
      "link",
      {
        "rel": "mask-icon",
        "href": "/blog/icons/safari-pinned-tab.svg",
        "color": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileImage",
        "content": "/icons/msapplication-icon-144x144.png"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileColor",
        "content": "#000000"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "bgImage": "assets/images/bg.jpg",
        "bgImageStyle": {
          "height": "400px"
        },
        "isShowTitleInHome": false
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-50e0f714",
      "path": "/"
    },
    {
      "title": "HHHH",
      "frontmatter": {},
      "regularPath": "/note/CSS/",
      "relativePath": "note/CSS/README.md",
      "key": "v-e0e09268",
      "path": "/note/CSS/"
    },
    {
      "title": "div水平垂直居中的方法",
      "frontmatter": {},
      "regularPath": "/note/CSS/DIV%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD.html",
      "relativePath": "note/CSS/DIV水平垂直居中.md",
      "key": "v-4c24a392",
      "path": "/note/CSS/DIV%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD.html",
      "headers": [
        {
          "level": 2,
          "title": "方法一:绝对定位方法1",
          "slug": "方法一-绝对定位方法1"
        },
        {
          "level": 2,
          "title": "方法二:绝对定位方法2",
          "slug": "方法二-绝对定位方法2"
        },
        {
          "level": 2,
          "title": "方法三:绝对定位方法3",
          "slug": "方法三-绝对定位方法3"
        },
        {
          "level": 2,
          "title": "方法四:flex",
          "slug": "方法四-flex"
        },
        {
          "level": 2,
          "title": "方法五:table特性",
          "slug": "方法五-table特性"
        },
        {
          "level": 2,
          "title": "方法六:绝对定位4",
          "slug": "方法六-绝对定位4"
        },
        {
          "level": 2,
          "title": "方法七:line-height",
          "slug": "方法七-line-height"
        }
      ]
    },
    {
      "title": "css 绘制三角形",
      "frontmatter": {},
      "regularPath": "/note/CSS/css%20%E5%AE%9E%E7%8E%B0%E4%B8%8A%E5%8F%B3%E4%B8%8B%E5%B7%A6%E4%B8%89%E8%A7%92.html",
      "relativePath": "note/CSS/css 实现上右下左三角.md",
      "key": "v-18d957c6",
      "path": "/note/CSS/css%20%E5%AE%9E%E7%8E%B0%E4%B8%8A%E5%8F%B3%E4%B8%8B%E5%B7%A6%E4%B8%89%E8%A7%92.html",
      "headers": [
        {
          "level": 2,
          "title": "右三角",
          "slug": "右三角"
        },
        {
          "level": 2,
          "title": "左三角",
          "slug": "左三角"
        },
        {
          "level": 2,
          "title": "下三角",
          "slug": "下三角"
        },
        {
          "level": 2,
          "title": "上三角",
          "slug": "上三角"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/note/CSS/mixin.html",
      "relativePath": "note/CSS/mixin.md",
      "key": "v-61c357fb",
      "path": "/note/CSS/mixin.html"
    },
    {
      "title": "CSS常见技巧汇总",
      "frontmatter": {},
      "regularPath": "/note/CSS/CSS%E9%AB%98%E7%BA%A7%E5%B8%B8%E8%A7%81%E6%8A%80%E5%B7%A7%E6%B1%87%E6%80%BB.html",
      "relativePath": "note/CSS/CSS高级常见技巧汇总.md",
      "key": "v-4173ef9e",
      "path": "/note/CSS/CSS%E9%AB%98%E7%BA%A7%E5%B8%B8%E8%A7%81%E6%8A%80%E5%B7%A7%E6%B1%87%E6%80%BB.html",
      "headers": [
        {
          "level": 2,
          "title": "1、设置input",
          "slug": "_1、设置input"
        },
        {
          "level": 2,
          "title": "2、单行和多行文本超出省略号",
          "slug": "_2、单行和多行文本超出省略号"
        },
        {
          "level": 2,
          "title": "3、负边距使用技巧",
          "slug": "_3、负边距使用技巧"
        },
        {
          "level": 2,
          "title": "4、outline属性的妙用技巧",
          "slug": "_4、outline属性的妙用技巧"
        },
        {
          "level": 2,
          "title": "5、虚线框绘制技巧",
          "slug": "_5、虚线框绘制技巧"
        },
        {
          "level": 2,
          "title": "6、隐藏文本的常用两种方法",
          "slug": "_6、隐藏文本的常用两种方法"
        },
        {
          "level": 2,
          "title": "7、表格",
          "slug": "_7、表格"
        },
        {
          "level": 2,
          "title": "8、卡券效果制作",
          "slug": "_8、卡券效果制作"
        }
      ]
    },
    {
      "title": "解决移动端 Retina 屏幕 1px 边框问题",
      "frontmatter": {},
      "regularPath": "/note/CSS/retina%E5%B1%8F%E5%B9%951px%E8%BE%B9%E6%A1%86%E9%97%AE%E9%A2%98.html",
      "relativePath": "note/CSS/retina屏幕1px边框问题.md",
      "key": "v-896af054",
      "path": "/note/CSS/retina%E5%B1%8F%E5%B9%951px%E8%BE%B9%E6%A1%86%E9%97%AE%E9%A2%98.html",
      "headers": [
        {
          "level": 2,
          "title": "一、概念",
          "slug": "一、概念"
        },
        {
          "level": 2,
          "title": "二、造成边框变粗的原因",
          "slug": "二、造成边框变粗的原因"
        },
        {
          "level": 2,
          "title": "三、解决边框变粗的8种办法",
          "slug": "三、解决边框变粗的8种办法"
        },
        {
          "level": 3,
          "title": "1、0.5px边框",
          "slug": "_1、0-5px边框"
        },
        {
          "level": 3,
          "title": "2、border-image",
          "slug": "_2、border-image"
        },
        {
          "level": 3,
          "title": "3、background-image",
          "slug": "_3、background-image"
        },
        {
          "level": 3,
          "title": "4、多背景渐变实现",
          "slug": "_4、多背景渐变实现"
        },
        {
          "level": 3,
          "title": "5、使用box-shadow模拟边框",
          "slug": "_5、使用box-shadow模拟边框"
        },
        {
          "level": 3,
          "title": "6、viewport + rem",
          "slug": "_6、viewport-rem"
        },
        {
          "level": 3,
          "title": "7、伪类 + transform",
          "slug": "_7、伪类-transform"
        },
        {
          "level": 3,
          "title": "8、svg",
          "slug": "_8、svg"
        },
        {
          "level": 2,
          "title": "四、总结",
          "slug": "四、总结"
        }
      ]
    },
    {
      "title": "sass笔记",
      "frontmatter": {},
      "regularPath": "/note/CSS/sass.html",
      "relativePath": "note/CSS/sass.md",
      "key": "v-39e44bdf",
      "path": "/note/CSS/sass.html",
      "headers": [
        {
          "level": 2,
          "title": "sass笔记",
          "slug": "sass笔记"
        },
        {
          "level": 3,
          "title": "一、配置自动编译",
          "slug": "一、配置自动编译"
        },
        {
          "level": 3,
          "title": "二、注释",
          "slug": "二、注释"
        },
        {
          "level": 3,
          "title": "三、变量",
          "slug": "三、变量"
        },
        {
          "level": 3,
          "title": "四、混合宏 Mixin",
          "slug": "四、混合宏-mixin"
        },
        {
          "level": 3,
          "title": "五、嵌套",
          "slug": "五、嵌套"
        },
        {
          "level": 3,
          "title": "六、Import （导入）",
          "slug": "六、import-导入"
        },
        {
          "level": 3,
          "title": "七、继承extend",
          "slug": "七、继承extend"
        },
        {
          "level": 3,
          "title": "占位符 placeholder",
          "slug": "占位符-placeholder"
        },
        {
          "level": 3,
          "title": "八、函数-运算",
          "slug": "八、函数-运算"
        },
        {
          "level": 3,
          "title": "九、函数-内置函数",
          "slug": "九、函数-内置函数"
        }
      ]
    },
    {
      "title": "移动端适配谷朊粉",
      "frontmatter": {},
      "regularPath": "/note/CSS/%E5%A4%A7%E5%B1%8F%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html",
      "relativePath": "note/CSS/大屏适配方案.md",
      "key": "v-4bd53062",
      "path": "/note/CSS/%E5%A4%A7%E5%B1%8F%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html"
    },
    {
      "title": "字体文件的引用和压缩",
      "frontmatter": {},
      "regularPath": "/note/CSS/%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E7%9A%84%E5%BC%95%E7%94%A8%E5%92%8C%E5%8E%8B%E7%BC%A9.html",
      "relativePath": "note/CSS/字体文件的引用和压缩.md",
      "key": "v-2d6dd408",
      "path": "/note/CSS/%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E7%9A%84%E5%BC%95%E7%94%A8%E5%92%8C%E5%8E%8B%E7%BC%A9.html",
      "headers": [
        {
          "level": 2,
          "title": "字体文件的引用和压缩",
          "slug": "字体文件的引用和压缩"
        },
        {
          "level": 3,
          "title": "一、项目需求",
          "slug": "一、项目需求"
        },
        {
          "level": 3,
          "title": "二、css引入字体",
          "slug": "二、css引入字体"
        },
        {
          "level": 3,
          "title": "三、软件-Fontmin",
          "slug": "三、软件-fontmin"
        },
        {
          "level": 3,
          "title": "四、插件-font-spider(字蛛)",
          "slug": "四、插件-font-spider-字蛛"
        },
        {
          "level": 3,
          "title": "五、注意",
          "slug": "五、注意"
        }
      ]
    },
    {
      "title": "CSS3新特性",
      "frontmatter": {
        "title": "CSS3新特性",
        "sidebarDepth": 2,
        "tags": [
          "CSS"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/note/CSS/%E6%B8%90%E5%8F%98.html",
      "relativePath": "note/CSS/渐变.md",
      "key": "v-5a7b5e90",
      "path": "/note/CSS/%E6%B8%90%E5%8F%98.html",
      "headers": [
        {
          "level": 2,
          "title": "字体渐变",
          "slug": "字体渐变"
        },
        {
          "level": 2,
          "title": "背景渐变",
          "slug": "背景渐变"
        },
        {
          "level": 2,
          "title": "透明度兼容问题",
          "slug": "透明度兼容问题"
        }
      ]
    },
    {
      "title": "移动端适配谷朊粉",
      "frontmatter": {},
      "regularPath": "/note/CSS/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html",
      "relativePath": "note/CSS/移动端适配方案.md",
      "key": "v-7257daa5",
      "path": "/note/CSS/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/note/HTML/Canvas%E5%92%8CSVG%E7%9A%84%E5%8C%BA%E5%88%AB.html",
      "relativePath": "note/HTML/Canvas和SVG的区别.md",
      "key": "v-da936c72",
      "path": "/note/HTML/Canvas%E5%92%8CSVG%E7%9A%84%E5%8C%BA%E5%88%AB.html"
    },
    {
      "title": "隐藏滚动条或更改滚动条样式",
      "frontmatter": {},
      "regularPath": "/note/CSS/%E9%9A%90%E8%97%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%88%96%E6%9B%B4%E6%94%B9%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%A0%B7%E5%BC%8F.html",
      "relativePath": "note/CSS/隐藏滚动条或更改滚动条样式.md",
      "key": "v-5ac3a38d",
      "path": "/note/CSS/%E9%9A%90%E8%97%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%88%96%E6%9B%B4%E6%94%B9%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%A0%B7%E5%BC%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "隐藏滚动条或更改滚动条样式",
          "slug": "隐藏滚动条或更改滚动条样式"
        }
      ]
    },
    {
      "title": "audio常用属性",
      "frontmatter": {},
      "regularPath": "/note/HTML/audio%E6%A0%87%E7%AD%BE%E5%B8%B8%E7%94%A8api.html",
      "relativePath": "note/HTML/audio标签常用api.md",
      "key": "v-140730de",
      "path": "/note/HTML/audio%E6%A0%87%E7%AD%BE%E5%B8%B8%E7%94%A8api.html",
      "headers": [
        {
          "level": 3,
          "title": "audio常用属性",
          "slug": "audio常用属性"
        },
        {
          "level": 3,
          "title": "audio音乐格式的支持",
          "slug": "audio音乐格式的支持"
        },
        {
          "level": 3,
          "title": "audio属性",
          "slug": "audio属性"
        },
        {
          "level": 3,
          "title": "常用audio的事件：",
          "slug": "常用audio的事件"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/note/CSS/%E8%AE%BE%E7%BD%AEinput.html",
      "relativePath": "note/CSS/设置input.md",
      "key": "v-5e1b87bb",
      "path": "/note/CSS/%E8%AE%BE%E7%BD%AEinput.html"
    },
    {
      "title": "canvas在标签中设置高，与再style中设置宽高有什么区别",
      "frontmatter": {},
      "regularPath": "/note/HTML/canvas.html",
      "relativePath": "note/HTML/canvas.md",
      "key": "v-daeef31a",
      "path": "/note/HTML/canvas.html",
      "headers": [
        {
          "level": 3,
          "title": "canvas在标签中设置高，与再style中设置宽高有什么区别",
          "slug": "canvas在标签中设置高-与再style中设置宽高有什么区别"
        }
      ]
    },
    {
      "title": "一台设备的dpr，是否会可变？",
      "frontmatter": {},
      "regularPath": "/note/HTML/dpr%E3%80%81%E8%AE%BE%E5%A4%87%E5%83%8F%E7%B4%A0%E3%80%81CSS%E5%83%8F%E7%B4%A0.html",
      "relativePath": "note/HTML/dpr、设备像素、CSS像素.md",
      "key": "v-057a5a9c",
      "path": "/note/HTML/dpr%E3%80%81%E8%AE%BE%E5%A4%87%E5%83%8F%E7%B4%A0%E3%80%81CSS%E5%83%8F%E7%B4%A0.html",
      "headers": [
        {
          "level": 3,
          "title": "一台设备的dpr，是否会可变？",
          "slug": "一台设备的dpr-是否会可变"
        }
      ]
    },
    {
      "title": "1、新增选择器",
      "frontmatter": {},
      "regularPath": "/note/HTML/h5%E6%96%B0%E7%89%B9%E6%80%A7.html",
      "relativePath": "note/HTML/h5新特性.md",
      "key": "v-1e565195",
      "path": "/note/HTML/h5%E6%96%B0%E7%89%B9%E6%80%A7.html",
      "headers": [
        {
          "level": 3,
          "title": "1、新增选择器",
          "slug": "_1、新增选择器"
        },
        {
          "level": 3,
          "title": "2、拖拽释放API",
          "slug": "_2、拖拽释放api"
        },
        {
          "level": 3,
          "title": "3、媒体播放器 video和audio",
          "slug": "_3、媒体播放器-video和audio"
        },
        {
          "level": 3,
          "title": "4、本地存储localStorage 和 sessionStorage",
          "slug": "_4、本地存储localstorage-和-sessionstorage"
        },
        {
          "level": 3,
          "title": "5、离线应用 manifest",
          "slug": "_5、离线应用-manifest"
        },
        {
          "level": 3,
          "title": "6、桌面通知 Notifications",
          "slug": "_6、桌面通知-notifications"
        },
        {
          "level": 3,
          "title": "7、语义化标签",
          "slug": "_7、语义化标签"
        },
        {
          "level": 3,
          "title": "8、增强表单控制 calendar、date、time、email、url、search",
          "slug": "_8、增强表单控制-calendar、date、time、email、url、search"
        },
        {
          "level": 3,
          "title": "9、地理定位",
          "slug": "_9、地理定位"
        },
        {
          "level": 3,
          "title": "10、多任务 webworker",
          "slug": "_10、多任务-webworker"
        },
        {
          "level": 3,
          "title": "11、全双工通讯协议 websocket",
          "slug": "_11、全双工通讯协议-websocket"
        },
        {
          "level": 3,
          "title": "12、历史管理 history",
          "slug": "_12、历史管理-history"
        },
        {
          "level": 3,
          "title": "13、跨域资源共享(CORS) Access-Control-Allow-Origin",
          "slug": "_13、跨域资源共享-cors-access-control-allow-origin"
        },
        {
          "level": 3,
          "title": "14、页面可见性改变事件 visibilitychange",
          "slug": "_14、页面可见性改变事件-visibilitychange"
        },
        {
          "level": 3,
          "title": "15、跨窗口通讯PostMessage",
          "slug": "_15、跨窗口通讯postmessage"
        },
        {
          "level": 3,
          "title": "16、Form Data对象",
          "slug": "_16、form-data对象"
        },
        {
          "level": 3,
          "title": "17、绘画canvas",
          "slug": "_17、绘画canvas"
        }
      ]
    },
    {
      "title": "meta viewport 相关",
      "frontmatter": {},
      "regularPath": "/note/HTML/meta.html",
      "relativePath": "note/HTML/meta.md",
      "key": "v-549cc44e",
      "path": "/note/HTML/meta.html",
      "headers": [
        {
          "level": 2,
          "title": "meta viewport 相关",
          "slug": "meta-viewport-相关"
        },
        {
          "level": 2,
          "title": "常用的meta元素有哪些",
          "slug": "常用的meta元素有哪些"
        },
        {
          "level": 2,
          "title": "charset",
          "slug": "charset"
        },
        {
          "level": 3,
          "title": "name&content",
          "slug": "name-content"
        },
        {
          "level": 3,
          "title": "http-equiv&content",
          "slug": "http-equiv-content"
        },
        {
          "level": 3,
          "title": "property&content",
          "slug": "property-content"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/note/HTML/h5%E8%AF%AD%E4%B9%89%E5%8C%96%E6%A0%87%E7%AD%BE.html",
      "relativePath": "note/HTML/h5语义化标签.md",
      "key": "v-3cdbaef4",
      "path": "/note/HTML/h5%E8%AF%AD%E4%B9%89%E5%8C%96%E6%A0%87%E7%AD%BE.html"
    },
    {
      "title": "script 标签为什么建议放在body标签的底部",
      "frontmatter": {},
      "regularPath": "/note/HTML/script.html",
      "relativePath": "note/HTML/script.md",
      "key": "v-075cb6cd",
      "path": "/note/HTML/script.html",
      "headers": [
        {
          "level": 3,
          "title": "script 标签为什么建议放在body标签的底部",
          "slug": "script-标签为什么建议放在body标签的底部"
        },
        {
          "level": 3,
          "title": "4、script 标签中 defer 和 async 的区别？",
          "slug": "_4、script-标签中-defer-和-async-的区别"
        }
      ]
    },
    {
      "title": "如何禁止input展示输入历史记录",
      "frontmatter": {},
      "regularPath": "/note/HTML/input.html",
      "relativePath": "note/HTML/input.md",
      "key": "v-32967ca5",
      "path": "/note/HTML/input.html",
      "headers": [
        {
          "level": 2,
          "title": "如何禁止input展示输入历史记录",
          "slug": "如何禁止input展示输入历史记录"
        },
        {
          "level": 2,
          "title": "input 指定上传文件类型",
          "slug": "input-指定上传文件类型"
        },
        {
          "level": 2,
          "title": "input上传文件可以同时选择多张吗？怎么设置？",
          "slug": "input上传文件可以同时选择多张吗-怎么设置"
        },
        {
          "level": 2,
          "title": "使用input标签上传图片时，怎么触发默认拍照功能？",
          "slug": "使用input标签上传图片时-怎么触发默认拍照功能"
        },
        {
          "level": 2,
          "title": "label标签的作用",
          "slug": "label标签的作用"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/note/HTML/video.html",
      "relativePath": "note/HTML/video.md",
      "key": "v-fbb1ff76",
      "path": "/note/HTML/video.html"
    },
    {
      "title": "为什么会利用多个域名来存储网站资源更有效？",
      "frontmatter": {},
      "regularPath": "/note/HTML/%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E5%88%A9%E7%94%A8%E5%A4%9A%E4%B8%AA%E5%9F%9F%E5%90%8D%E6%9D%A5%E5%AD%98%E5%82%A8%E7%BD%91%E7%AB%99%E8%B5%84%E6%BA%90%E6%9B%B4%E6%9C%89%E6%95%88%EF%BC%9F.html",
      "relativePath": "note/HTML/为什么会利用多个域名来存储网站资源更有效？.md",
      "key": "v-22dbdfb6",
      "path": "/note/HTML/%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E5%88%A9%E7%94%A8%E5%A4%9A%E4%B8%AA%E5%9F%9F%E5%90%8D%E6%9D%A5%E5%AD%98%E5%82%A8%E7%BD%91%E7%AB%99%E8%B5%84%E6%BA%90%E6%9B%B4%E6%9C%89%E6%95%88%EF%BC%9F.html",
      "headers": [
        {
          "level": 2,
          "title": "为什么会利用多个域名来存储网站资源更有效？",
          "slug": "为什么会利用多个域名来存储网站资源更有效"
        },
        {
          "level": 3,
          "title": "1、CDN缓存更方便",
          "slug": "_1、cdn缓存更方便"
        },
        {
          "level": 3,
          "title": "2、突破浏览器并发限制",
          "slug": "_2、突破浏览器并发限制"
        },
        {
          "level": 3,
          "title": "3、节约cookie带宽",
          "slug": "_3、节约cookie带宽"
        },
        {
          "level": 3,
          "title": "4、节约主域名的连接数，优化页面响应速度",
          "slug": "_4、节约主域名的连接数-优化页面响应速度"
        },
        {
          "level": 3,
          "title": "5、防止不必要的安全问题",
          "slug": "_5、防止不必要的安全问题"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/note/HTML/iframe%E7%9A%84%E4%BC%98%E7%82%B9%E3%80%81%E7%BC%BA%E7%82%B9.html",
      "relativePath": "note/HTML/iframe的优点、缺点.md",
      "key": "v-0eb10efa",
      "path": "/note/HTML/iframe%E7%9A%84%E4%BC%98%E7%82%B9%E3%80%81%E7%BC%BA%E7%82%B9.html",
      "headers": [
        {
          "level": 2,
          "title": "一、iframe的优点：",
          "slug": "一、iframe的优点"
        },
        {
          "level": 2,
          "title": "二、iframe的缺点：",
          "slug": "二、iframe的缺点"
        }
      ]
    },
    {
      "title": "style 标签写在 body 后与 body 前有什么区别？",
      "frontmatter": {},
      "regularPath": "/note/HTML/style%20%E6%A0%87%E7%AD%BE%E5%86%99%E5%9C%A8%20body%20%E5%90%8E%E4%B8%8E%20body%20%E5%89%8D%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB%EF%BC%9F.html",
      "relativePath": "note/HTML/style 标签写在 body 后与 body 前有什么区别？.md",
      "key": "v-6d32acc1",
      "path": "/note/HTML/style%20%E6%A0%87%E7%AD%BE%E5%86%99%E5%9C%A8%20body%20%E5%90%8E%E4%B8%8E%20body%20%E5%89%8D%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB%EF%BC%9F.html",
      "headers": [
        {
          "level": 2,
          "title": "style 标签写在 body 后与 body 前有什么区别？",
          "slug": "style-标签写在-body-后与-body-前有什么区别"
        }
      ]
    },
    {
      "title": "Doctype 作用？严格模式与混杂模式如何区分？它们有何意义？",
      "frontmatter": {},
      "regularPath": "/note/HTML/%E5%85%B6%E4%BB%96%E7%AE%80%E7%AD%94%E9%A2%98.html",
      "relativePath": "note/HTML/其他简答题.md",
      "key": "v-61c0020b",
      "path": "/note/HTML/%E5%85%B6%E4%BB%96%E7%AE%80%E7%AD%94%E9%A2%98.html",
      "headers": [
        {
          "level": 2,
          "title": "Doctype 作用？严格模式与混杂模式如何区分？它们有何意义？",
          "slug": "doctype-作用-严格模式与混杂模式如何区分-它们有何意义"
        },
        {
          "level": 2,
          "title": "什么是DOM和BOM？",
          "slug": "什么是dom和bom"
        },
        {
          "level": 2,
          "title": "1、列出常见的行内元素、块级元素、空(void)元素？",
          "slug": "_1、列出常见的行内元素、块级元素、空-void-元素"
        },
        {
          "level": 2,
          "title": "Js 动画与 CSS 动画区别及相应实现",
          "slug": "js-动画与-css-动画区别及相应实现"
        },
        {
          "level": 2,
          "title": "html 和css中图片加载与渲染规则是什么样的？",
          "slug": "html-和css中图片加载与渲染规则是什么样的"
        }
      ]
    },
    {
      "title": "前端需要注意哪些SEO",
      "frontmatter": {},
      "regularPath": "/note/HTML/%E5%89%8D%E7%AB%AF%E9%9C%80%E8%A6%81%E6%B3%A8%E6%84%8F%E5%93%AA%E4%BA%9BSEO.html",
      "relativePath": "note/HTML/前端需要注意哪些SEO.md",
      "key": "v-435a9109",
      "path": "/note/HTML/%E5%89%8D%E7%AB%AF%E9%9C%80%E8%A6%81%E6%B3%A8%E6%84%8F%E5%93%AA%E4%BA%9BSEO.html",
      "headers": [
        {
          "level": 2,
          "title": "前端需要注意哪些SEO",
          "slug": "前端需要注意哪些seo"
        }
      ]
    },
    {
      "title": "如何禁止a标签跳转页面或者定位链接？",
      "frontmatter": {},
      "regularPath": "/note/HTML/%E5%A6%82%E4%BD%95%E7%A6%81%E6%AD%A2a%E6%A0%87%E7%AD%BE%E8%B7%B3%E8%BD%AC%E9%A1%B5%E9%9D%A2%E6%88%96%E8%80%85%E5%AE%9A%E4%BD%8D%E9%93%BE%E6%8E%A5%EF%BC%9F.html",
      "relativePath": "note/HTML/如何禁止a标签跳转页面或者定位链接？.md",
      "key": "v-57b9fbcb",
      "path": "/note/HTML/%E5%A6%82%E4%BD%95%E7%A6%81%E6%AD%A2a%E6%A0%87%E7%AD%BE%E8%B7%B3%E8%BD%AC%E9%A1%B5%E9%9D%A2%E6%88%96%E8%80%85%E5%AE%9A%E4%BD%8D%E9%93%BE%E6%8E%A5%EF%BC%9F.html",
      "headers": [
        {
          "level": 3,
          "title": "如何禁止a标签跳转页面或者定位链接？",
          "slug": "如何禁止a标签跳转页面或者定位链接"
        }
      ]
    },
    {
      "title": "什么是渐进增强和优雅降级？",
      "frontmatter": {},
      "regularPath": "/note/HTML/%E6%B8%90%E8%BF%9B%E5%A2%9E%E5%BC%BA%E5%92%8C%E4%BC%98%E9%9B%85%E9%99%8D%E7%BA%A7.html",
      "relativePath": "note/HTML/渐进增强和优雅降级.md",
      "key": "v-f9edc4a2",
      "path": "/note/HTML/%E6%B8%90%E8%BF%9B%E5%A2%9E%E5%BC%BA%E5%92%8C%E4%BC%98%E9%9B%85%E9%99%8D%E7%BA%A7.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是渐进增强和优雅降级？",
          "slug": "什么是渐进增强和优雅降级"
        }
      ]
    },
    {
      "title": "知道的网页制作会用到的图片格式有哪些",
      "frontmatter": {},
      "regularPath": "/note/HTML/%E5%9B%BE%E7%89%87.html",
      "relativePath": "note/HTML/图片.md",
      "key": "v-4bc1ce98",
      "path": "/note/HTML/%E5%9B%BE%E7%89%87.html",
      "headers": [
        {
          "level": 2,
          "title": "知道的网页制作会用到的图片格式有哪些",
          "slug": "知道的网页制作会用到的图片格式有哪些"
        },
        {
          "level": 2,
          "title": "前端该如何选择图片的格式？",
          "slug": "前端该如何选择图片的格式"
        },
        {
          "level": 3,
          "title": "位图、矢量图",
          "slug": "位图、矢量图"
        },
        {
          "level": 3,
          "title": "图片的压缩类型",
          "slug": "图片的压缩类型"
        },
        {
          "level": 3,
          "title": "图片位数",
          "slug": "图片位数"
        },
        {
          "level": 3,
          "title": "常见的图片的格式",
          "slug": "常见的图片的格式"
        }
      ]
    },
    {
      "title": "如何实现浏览器内多个标签也之间的通信",
      "frontmatter": {},
      "regularPath": "/note/HTML/%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0%E6%B5%8F%E8%A7%88%E5%99%A8%E5%86%85%E5%A4%9A%E4%B8%AA%E6%A0%87%E7%AD%BE%E4%B9%9F%E4%B9%8B%E9%97%B4%E7%9A%84%E9%80%9A%E4%BF%A1.html",
      "relativePath": "note/HTML/如何实现浏览器内多个标签也之间的通信.md",
      "key": "v-5c4a2edf",
      "path": "/note/HTML/%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0%E6%B5%8F%E8%A7%88%E5%99%A8%E5%86%85%E5%A4%9A%E4%B8%AA%E6%A0%87%E7%AD%BE%E4%B9%9F%E4%B9%8B%E9%97%B4%E7%9A%84%E9%80%9A%E4%BF%A1.html",
      "headers": [
        {
          "level": 2,
          "title": "如何实现浏览器内多个标签也之间的通信",
          "slug": "如何实现浏览器内多个标签也之间的通信"
        },
        {
          "level": 3,
          "title": "localStorage",
          "slug": "localstorage"
        },
        {
          "level": 3,
          "title": "SharedWorker",
          "slug": "sharedworker"
        },
        {
          "level": 3,
          "title": "WebSocket 通讯",
          "slug": "websocket-通讯"
        },
        {
          "level": 3,
          "title": "定时器 setlnterval + cookie",
          "slug": "定时器-setlnterval-cookie"
        },
        {
          "level": 3,
          "title": "postMessage",
          "slug": "postmessage"
        }
      ]
    },
    {
      "title": "简述一下src与href的区别",
      "frontmatter": {},
      "regularPath": "/note/HTML/%E7%AE%80%E8%BF%B0%E4%B8%80%E4%B8%8Bsrc%E4%B8%8Ehref%E7%9A%84%E5%8C%BA%E5%88%AB.html",
      "relativePath": "note/HTML/简述一下src与href的区别.md",
      "key": "v-5c9c562d",
      "path": "/note/HTML/%E7%AE%80%E8%BF%B0%E4%B8%80%E4%B8%8Bsrc%E4%B8%8Ehref%E7%9A%84%E5%8C%BA%E5%88%AB.html",
      "headers": [
        {
          "level": 3,
          "title": "简述一下src与href的区别",
          "slug": "简述一下src与href的区别"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "CSS Tags"
      },
      "regularPath": "/tag/CSS/",
      "key": "v-3259a754",
      "path": "/tag/CSS/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "CSS Categories"
      },
      "regularPath": "/categories/CSS/",
      "key": "v-7efe64ca",
      "path": "/categories/CSS/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "nav": [
      {
        "text": "Home",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "博客园",
        "link": "https://www.cnblogs.com/jiajia-hjj/",
        "icon": "reco-blog"
      },
      {
        "text": "GitHub",
        "link": "https://github.com/smallsunnyfox",
        "icon": "reco-github"
      }
    ],
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "Tag"
      }
    },
    "logo": "/assets/images/head.jpg",
    "search": true,
    "searchMaxSuggestions": 10,
    "subSidebar": "auto",
    "sidebarDepth": 2,
    "displayAllHeaders": false,
    "sidebar": {
      "/note/HTML/": [
        {
          "title": "HTML",
          "children": [
            "audio标签常用api",
            "canvas",
            "Canvas和SVG的区别",
            "dpr、设备像素、CSS像素",
            "h5新特性",
            "h5语义化标签",
            "iframe的优点、缺点",
            "input",
            "meta",
            "script",
            "style 标签写在 body 后与 body 前有什么区别？",
            "video",
            "为什么会利用多个域名来存储网站资源更有效？",
            "其他简答题",
            "前端需要注意哪些SEO",
            "图片",
            "如何实现浏览器内多个标签也之间的通信",
            "如何禁止a标签跳转页面或者定位链接？",
            "渐进增强和优雅降级",
            "简述一下src与href的区别"
          ]
        }
      ],
      "/note/CSS/": [
        {
          "title": "CSS",
          "children": [
            "css 实现上右下左三角",
            "CSS高级常见技巧汇总",
            "DIV水平垂直居中",
            "mixin",
            "",
            "retina屏幕1px边框问题",
            "sass",
            "大屏适配方案",
            "字体文件的引用和压缩",
            "渐变",
            "移动端适配方案",
            "设置input",
            "隐藏滚动条或更改滚动条样式"
          ]
        }
      ],
      "/note/": [
        {
          "title": "note",
          "children": []
        }
      ]
    },
    "lastUpdated": "Last Updated",
    "author": "HHH",
    "authorAvatar": "assets/images/head.jpg",
    "startYear": "2022",
    "valineConfig": {
      "appId": "XDwlSXS2pD137bPrPpwQaqqD-gzGzoHsz",
      "appKey": "CQ8FKrMUP76LwycPcKlDoRqV",
      "placeholder": "是时候展现真正的技术了",
      "avatar": "wavatar",
      "serverUrl": "https://leanserver.smallsunnyfox.com"
    }
  }
}