/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "HHH",
  "description": "一个小小前端的学习笔记!",
  "base": "/blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "HJJ"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "一个小小前端的学习笔记!"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/manifest.json"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/icons/apple-touch-icon.png"
      }
    ],
    [
      "link",
      {
        "rel": "mask-icon",
        "href": "/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/blog/icons/safari-pinned-tab.svg",
        "color": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileImage",
        "content": "/icons/msapplication-icon-144x144.png"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileColor",
        "content": "#000000"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "heroText": "小小前端",
        "tagline": "今天又是想变成大佬的一天！",
        "home": true,
        "bgImage": "assets/images/bg.jpg",
        "bgImageStyle": {
          "height": "400px"
        },
        "isShowTitleInHome": false
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-50e0f714",
      "path": "/",
      "lastUpdated": "2022-05-02 1:32:54",
      "lastUpdatedTimestamp": 1651469574000
    },
    {
      "title": "CSS常见技巧汇总",
      "frontmatter": {
        "title": "CSS常见技巧汇总",
        "tags": [
          "CSS"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/note/CSS/CSS%E9%AB%98%E7%BA%A7%E5%B8%B8%E8%A7%81%E6%8A%80%E5%B7%A7%E6%B1%87%E6%80%BB.html",
      "relativePath": "note/CSS/CSS高级常见技巧汇总.md",
      "key": "v-4173ef9e",
      "path": "/note/CSS/CSS%E9%AB%98%E7%BA%A7%E5%B8%B8%E8%A7%81%E6%8A%80%E5%B7%A7%E6%B1%87%E6%80%BB.html",
      "headers": [
        {
          "level": 2,
          "title": "1、设置 input",
          "slug": "_1、设置-input"
        },
        {
          "level": 2,
          "title": "2、单行和多行文本超出省略号",
          "slug": "_2、单行和多行文本超出省略号"
        },
        {
          "level": 2,
          "title": "3、负边距使用技巧",
          "slug": "_3、负边距使用技巧"
        },
        {
          "level": 2,
          "title": "4、outline 属性的妙用技巧",
          "slug": "_4、outline-属性的妙用技巧"
        },
        {
          "level": 2,
          "title": "5、虚线框绘制技巧",
          "slug": "_5、虚线框绘制技巧"
        },
        {
          "level": 2,
          "title": "6、隐藏文本的常用两种方法",
          "slug": "_6、隐藏文本的常用两种方法"
        },
        {
          "level": 2,
          "title": "7、表格",
          "slug": "_7、表格"
        },
        {
          "level": 2,
          "title": "8、卡券效果制作",
          "slug": "_8、卡券效果制作"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "绘制三角形",
      "frontmatter": {
        "title": "绘制三角形",
        "tags": [
          "CSS"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/note/CSS/css%20%E5%AE%9E%E7%8E%B0%E4%B8%8A%E5%8F%B3%E4%B8%8B%E5%B7%A6%E4%B8%89%E8%A7%92.html",
      "relativePath": "note/CSS/css 实现上右下左三角.md",
      "key": "v-18d957c6",
      "path": "/note/CSS/css%20%E5%AE%9E%E7%8E%B0%E4%B8%8A%E5%8F%B3%E4%B8%8B%E5%B7%A6%E4%B8%89%E8%A7%92.html",
      "headers": [
        {
          "level": 2,
          "title": "一、右三角",
          "slug": "一、右三角"
        },
        {
          "level": 2,
          "title": "二、左三角",
          "slug": "二、左三角"
        },
        {
          "level": 2,
          "title": "三、下三角",
          "slug": "三、下三角"
        },
        {
          "level": 2,
          "title": "四、上三角",
          "slug": "四、上三角"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "div水平垂直居中的方法",
      "frontmatter": {
        "title": "div水平垂直居中的方法",
        "tags": [
          "CSS"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/note/CSS/DIV%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD.html",
      "relativePath": "note/CSS/DIV水平垂直居中.md",
      "key": "v-4c24a392",
      "path": "/note/CSS/DIV%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD.html",
      "headers": [
        {
          "level": 2,
          "title": "方法一:绝对定位方法 1",
          "slug": "方法一-绝对定位方法-1"
        },
        {
          "level": 2,
          "title": "方法二:绝对定位方法 2",
          "slug": "方法二-绝对定位方法-2"
        },
        {
          "level": 2,
          "title": "方法三:绝对定位方法 3",
          "slug": "方法三-绝对定位方法-3"
        },
        {
          "level": 2,
          "title": "方法四:flex",
          "slug": "方法四-flex"
        },
        {
          "level": 2,
          "title": "方法五:table 特性",
          "slug": "方法五-table-特性"
        },
        {
          "level": 2,
          "title": "方法六:绝对定位 4",
          "slug": "方法六-绝对定位-4"
        },
        {
          "level": 2,
          "title": "方法七:line-height",
          "slug": "方法七-line-height"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "解决移动端 Retina 屏幕 1px 边框问题",
      "frontmatter": {
        "title": "解决移动端 Retina 屏幕 1px 边框问题",
        "tags": [
          "CSS"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/note/CSS/retina%E5%B1%8F%E5%B9%951px%E8%BE%B9%E6%A1%86%E9%97%AE%E9%A2%98.html",
      "relativePath": "note/CSS/retina屏幕1px边框问题.md",
      "key": "v-896af054",
      "path": "/note/CSS/retina%E5%B1%8F%E5%B9%951px%E8%BE%B9%E6%A1%86%E9%97%AE%E9%A2%98.html",
      "headers": [
        {
          "level": 2,
          "title": "一、概念",
          "slug": "一、概念"
        },
        {
          "level": 2,
          "title": "二、造成边框变粗的原因",
          "slug": "二、造成边框变粗的原因"
        },
        {
          "level": 2,
          "title": "三、解决边框变粗的 8 种办法",
          "slug": "三、解决边框变粗的-8-种办法"
        },
        {
          "level": 3,
          "title": "1、0.5px 边框",
          "slug": "_1、0-5px-边框"
        },
        {
          "level": 3,
          "title": "2、border-image",
          "slug": "_2、border-image"
        },
        {
          "level": 3,
          "title": "3、background-image",
          "slug": "_3、background-image"
        },
        {
          "level": 3,
          "title": "4、多背景渐变实现",
          "slug": "_4、多背景渐变实现"
        },
        {
          "level": 3,
          "title": "5、使用 box-shadow 模拟边框",
          "slug": "_5、使用-box-shadow-模拟边框"
        },
        {
          "level": 3,
          "title": "6、viewport + rem",
          "slug": "_6、viewport-rem"
        },
        {
          "level": 3,
          "title": "7、伪类 + transform",
          "slug": "_7、伪类-transform"
        },
        {
          "level": 3,
          "title": "8、svg",
          "slug": "_8、svg"
        },
        {
          "level": 2,
          "title": "四、总结",
          "slug": "四、总结"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "_mixin.scss",
      "frontmatter": {
        "title": "_mixin.scss",
        "tags": [
          "CSS"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/note/CSS/mixin.html",
      "relativePath": "note/CSS/mixin.md",
      "key": "v-61c357fb",
      "path": "/note/CSS/mixin.html",
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "字体文件的引用和压缩",
      "frontmatter": {
        "title": "字体文件的引用和压缩",
        "tags": [
          "CSS"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/note/CSS/%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E7%9A%84%E5%BC%95%E7%94%A8%E5%92%8C%E5%8E%8B%E7%BC%A9.html",
      "relativePath": "note/CSS/字体文件的引用和压缩.md",
      "key": "v-2d6dd408",
      "path": "/note/CSS/%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%E7%9A%84%E5%BC%95%E7%94%A8%E5%92%8C%E5%8E%8B%E7%BC%A9.html",
      "headers": [
        {
          "level": 2,
          "title": "一、项目需求",
          "slug": "一、项目需求"
        },
        {
          "level": 2,
          "title": "二、css 引入字体",
          "slug": "二、css-引入字体"
        },
        {
          "level": 2,
          "title": "三、软件-Fontmin",
          "slug": "三、软件-fontmin"
        },
        {
          "level": 2,
          "title": "四、插件-font-spider(字蛛)",
          "slug": "四、插件-font-spider-字蛛"
        },
        {
          "level": 2,
          "title": "五、注意",
          "slug": "五、注意"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "sass笔记",
      "frontmatter": {
        "title": "sass笔记",
        "tags": [
          "CSS"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/note/CSS/sass.html",
      "relativePath": "note/CSS/sass.md",
      "key": "v-39e44bdf",
      "path": "/note/CSS/sass.html",
      "headers": [
        {
          "level": 2,
          "title": "sass 笔记",
          "slug": "sass-笔记"
        },
        {
          "level": 3,
          "title": "一、配置自动编译",
          "slug": "一、配置自动编译"
        },
        {
          "level": 3,
          "title": "二、注释",
          "slug": "二、注释"
        },
        {
          "level": 3,
          "title": "三、变量",
          "slug": "三、变量"
        },
        {
          "level": 3,
          "title": "四、混合宏 Mixin",
          "slug": "四、混合宏-mixin"
        },
        {
          "level": 3,
          "title": "五、嵌套",
          "slug": "五、嵌套"
        },
        {
          "level": 3,
          "title": "六、Import （导入）",
          "slug": "六、import-导入"
        },
        {
          "level": 3,
          "title": "七、继承 extend",
          "slug": "七、继承-extend"
        },
        {
          "level": 3,
          "title": "占位符 placeholder",
          "slug": "占位符-placeholder"
        },
        {
          "level": 3,
          "title": "八、函数-运算",
          "slug": "八、函数-运算"
        },
        {
          "level": 3,
          "title": "九、函数-内置函数",
          "slug": "九、函数-内置函数"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "移动端适配方案",
      "frontmatter": {
        "title": "移动端适配方案",
        "tags": [
          "CSS"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/note/CSS/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html",
      "relativePath": "note/CSS/移动端适配方案.md",
      "key": "v-7257daa5",
      "path": "/note/CSS/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html",
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "设置input",
      "frontmatter": {
        "title": "设置input",
        "tags": [
          "CSS"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/note/CSS/%E8%AE%BE%E7%BD%AEinput.html",
      "relativePath": "note/CSS/设置input.md",
      "key": "v-5e1b87bb",
      "path": "/note/CSS/%E8%AE%BE%E7%BD%AEinput.html",
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "隐藏滚动条或更改滚动条样式",
      "frontmatter": {
        "title": "隐藏滚动条或更改滚动条样式",
        "tags": [
          "CSS"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/note/CSS/%E9%9A%90%E8%97%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%88%96%E6%9B%B4%E6%94%B9%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%A0%B7%E5%BC%8F.html",
      "relativePath": "note/CSS/隐藏滚动条或更改滚动条样式.md",
      "key": "v-5ac3a38d",
      "path": "/note/CSS/%E9%9A%90%E8%97%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%88%96%E6%9B%B4%E6%94%B9%E6%BB%9A%E5%8A%A8%E6%9D%A1%E6%A0%B7%E5%BC%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "一、滚动条隐藏",
          "slug": "一、滚动条隐藏"
        },
        {
          "level": 2,
          "title": "二、更改滚动条样式",
          "slug": "二、更改滚动条样式"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "大屏适配方案",
      "frontmatter": {
        "title": "大屏适配方案",
        "tags": [
          "CSS"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/note/CSS/%E5%A4%A7%E5%B1%8F%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html",
      "relativePath": "note/CSS/大屏适配方案.md",
      "key": "v-4bd53062",
      "path": "/note/CSS/%E5%A4%A7%E5%B1%8F%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88.html",
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "渐变",
      "frontmatter": {
        "title": "渐变",
        "tags": [
          "CSS"
        ],
        "categories": [
          "CSS"
        ]
      },
      "regularPath": "/note/CSS/%E6%B8%90%E5%8F%98.html",
      "relativePath": "note/CSS/渐变.md",
      "key": "v-5a7b5e90",
      "path": "/note/CSS/%E6%B8%90%E5%8F%98.html",
      "headers": [
        {
          "level": 2,
          "title": "一、字体渐变",
          "slug": "一、字体渐变"
        },
        {
          "level": 2,
          "title": "二、背景渐变",
          "slug": "二、背景渐变"
        },
        {
          "level": 2,
          "title": "三、透明度兼容问题",
          "slug": "三、透明度兼容问题"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "Symbol()函数",
      "frontmatter": {},
      "regularPath": "/note/ES6/BigInt.html",
      "relativePath": "note/ES6/BigInt.md",
      "key": "v-1d36331f",
      "path": "/note/ES6/BigInt.html",
      "headers": [
        {
          "level": 2,
          "title": "基本使用",
          "slug": "基本使用"
        },
        {
          "level": 2,
          "title": "应用场景",
          "slug": "应用场景"
        },
        {
          "level": 2,
          "title": "方法",
          "slug": "方法"
        },
        {
          "level": 3,
          "title": "Symbol.for()",
          "slug": "symbol-for"
        },
        {
          "level": 3,
          "title": "Symbol.keyFor()",
          "slug": "symbol-keyfor"
        }
      ]
    },
    {
      "title": "Promise",
      "frontmatter": {},
      "regularPath": "/note/ES6/Promise.html",
      "relativePath": "note/ES6/Promise.md",
      "key": "v-23dc747d",
      "path": "/note/ES6/Promise.html",
      "headers": [
        {
          "level": 2,
          "title": "Promise",
          "slug": "promise"
        },
        {
          "level": 3,
          "title": "一、基本使用",
          "slug": "一、基本使用"
        },
        {
          "level": 3,
          "title": "二、捕捉错误",
          "slug": "二、捕捉错误"
        },
        {
          "level": 3,
          "title": "三、Promise.resolve()",
          "slug": "三、promise-resolve"
        },
        {
          "level": 3,
          "title": "四、Promise.reject()",
          "slug": "四、promise-reject"
        },
        {
          "level": 3,
          "title": "五、Promise.all()",
          "slug": "五、promise-all"
        },
        {
          "level": 3,
          "title": "六、Promise.race()",
          "slug": "六、promise-race"
        },
        {
          "level": 3,
          "title": "七、存在的问题：",
          "slug": "七、存在的问题"
        },
        {
          "level": 3,
          "title": "八、Promise解决回调信任问题",
          "slug": "八、promise解决回调信任问题"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/note/ES6/Promise%E4%B8%AD%E7%9A%84then%E3%80%81catch%E3%80%81finally.html",
      "relativePath": "note/ES6/Promise中的then、catch、finally.md",
      "key": "v-93864760",
      "path": "/note/ES6/Promise%E4%B8%AD%E7%9A%84then%E3%80%81catch%E3%80%81finally.html"
    },
    {
      "title": "Symbol()函数",
      "frontmatter": {},
      "regularPath": "/note/ES6/Symbol.html",
      "relativePath": "note/ES6/Symbol.md",
      "key": "v-6d1c0482",
      "path": "/note/ES6/Symbol.html",
      "headers": [
        {
          "level": 2,
          "title": "基本使用",
          "slug": "基本使用"
        },
        {
          "level": 2,
          "title": "应用场景",
          "slug": "应用场景"
        },
        {
          "level": 2,
          "title": "方法",
          "slug": "方法"
        },
        {
          "level": 3,
          "title": "Symbol.for()",
          "slug": "symbol-for"
        },
        {
          "level": 3,
          "title": "Symbol.keyFor()",
          "slug": "symbol-keyfor"
        }
      ]
    },
    {
      "title": "一、Set集合",
      "frontmatter": {},
      "regularPath": "/note/ES6/Set%E3%80%81Map.html",
      "relativePath": "note/ES6/Set、Map.md",
      "key": "v-4392f64c",
      "path": "/note/ES6/Set%E3%80%81Map.html",
      "headers": [
        {
          "level": 2,
          "title": "一、Set集合",
          "slug": "一、set集合"
        },
        {
          "level": 3,
          "title": "1.1.基本操作",
          "slug": "_1-1-基本操作"
        },
        {
          "level": 3,
          "title": "1.2.应用",
          "slug": "_1-2-应用"
        },
        {
          "level": 2,
          "title": "二、WeakSet",
          "slug": "二、weakset"
        },
        {
          "level": 3,
          "title": "2.1.与Set 的区别",
          "slug": "_2-1-与set-的区别"
        },
        {
          "level": 3,
          "title": "2.1.基本操作",
          "slug": "_2-1-基本操作"
        },
        {
          "level": 2,
          "title": "三、Map字典",
          "slug": "三、map字典"
        },
        {
          "level": 3,
          "title": "3.1.与 Objects 的区别",
          "slug": "_3-1-与-objects-的区别"
        },
        {
          "level": 3,
          "title": "3.2.基本操作",
          "slug": "_3-2-基本操作"
        },
        {
          "level": 3,
          "title": "3.3.应用",
          "slug": "_3-3-应用"
        },
        {
          "level": 2,
          "title": "四、WeakMap",
          "slug": "四、weakmap"
        },
        {
          "level": 3,
          "title": "4.1.与Map的区别",
          "slug": "_4-1-与map的区别"
        },
        {
          "level": 3,
          "title": "4.2.基本操作",
          "slug": "_4-2-基本操作"
        },
        {
          "level": 3,
          "title": "4.3.应用",
          "slug": "_4-3-应用"
        },
        {
          "level": 2,
          "title": "五、总结",
          "slug": "五、总结"
        }
      ]
    },
    {
      "title": "4. Promise中的all和race",
      "frontmatter": {},
      "regularPath": "/note/ES6/Promise%E4%B8%AD%E7%9A%84all%E5%92%8Crace.html",
      "relativePath": "note/ES6/Promise中的all和race.md",
      "key": "v-36ed3ae9",
      "path": "/note/ES6/Promise%E4%B8%AD%E7%9A%84all%E5%92%8Crace.html",
      "headers": [
        {
          "level": 3,
          "title": "4. Promise中的all和race",
          "slug": "_4-promise中的all和race"
        }
      ]
    },
    {
      "title": "async",
      "frontmatter": {},
      "regularPath": "/note/ES6/async%E5%87%BD%E6%95%B0.html",
      "relativePath": "note/ES6/async函数.md",
      "key": "v-90dc4ad0",
      "path": "/note/ES6/async%E5%87%BD%E6%95%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "一、基本使用",
          "slug": "一、基本使用"
        },
        {
          "level": 3,
          "title": "返回值",
          "slug": "返回值"
        },
        {
          "level": 3,
          "title": "await 表达式",
          "slug": "await-表达式"
        },
        {
          "level": 3,
          "title": "应用",
          "slug": "应用"
        },
        {
          "level": 2,
          "title": "二、async 函数的优点",
          "slug": "二、async-函数的优点"
        },
        {
          "level": 3,
          "title": "2.1.对比于Generator",
          "slug": "_2-1-对比于generator"
        },
        {
          "level": 3,
          "title": "2.2.对比于Promise",
          "slug": "_2-2-对比于promise"
        },
        {
          "level": 3,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "兼容性",
      "frontmatter": {},
      "regularPath": "/note/ES6/es6.html",
      "relativePath": "note/ES6/es6.md",
      "key": "v-114765a3",
      "path": "/note/ES6/es6.html",
      "headers": [
        {
          "level": 2,
          "title": "兼容性",
          "slug": "兼容性"
        },
        {
          "level": 2,
          "title": "let和const",
          "slug": "let和const"
        },
        {
          "level": 2,
          "title": "解构赋值",
          "slug": "解构赋值"
        },
        {
          "level": 2,
          "title": "字符串",
          "slug": "字符串"
        },
        {
          "level": 2,
          "title": "json",
          "slug": "json"
        },
        {
          "level": 2,
          "title": "",
          "slug": ""
        }
      ]
    },
    {
      "title": "es6 对象",
      "frontmatter": {},
      "regularPath": "/note/ES6/es6%E5%AF%B9%E8%B1%A1.html",
      "relativePath": "note/ES6/es6对象.md",
      "key": "v-29e5daa9",
      "path": "/note/ES6/es6%E5%AF%B9%E8%B1%A1.html",
      "headers": [
        {
          "level": 2,
          "title": "es6 对象",
          "slug": "es6-对象"
        },
        {
          "level": 2,
          "title": "一、对象字面量",
          "slug": "一、对象字面量"
        },
        {
          "level": 2,
          "title": "二、对象的新方法",
          "slug": "二、对象的新方法"
        },
        {
          "level": 3,
          "title": "2.1.Object.assign()",
          "slug": "_2-1-object-assign"
        },
        {
          "level": 3,
          "title": "2.2.Object.is()",
          "slug": "_2-2-object-is"
        },
        {
          "level": 2,
          "title": "三、class 类",
          "slug": "三、class-类"
        },
        {
          "level": 3,
          "title": "3.1.创建对象",
          "slug": "_3-1-创建对象"
        },
        {
          "level": 3,
          "title": "3.2.constructor方法",
          "slug": "_3-2-constructor方法"
        },
        {
          "level": 3,
          "title": "3.3.继承",
          "slug": "_3-3-继承"
        },
        {
          "level": 3,
          "title": "3.4.静态方法",
          "slug": "_3-4-静态方法"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/note/ES6/async-await.html",
      "relativePath": "note/ES6/async-await.md",
      "key": "v-0274d3e9",
      "path": "/note/ES6/async-await.html"
    },
    {
      "title": "解构赋值",
      "frontmatter": {},
      "regularPath": "/note/ES6/es6%E8%A7%A3%E6%9E%84%E8%B5%8B%E5%80%BC.html",
      "relativePath": "note/ES6/es6解构赋值.md",
      "key": "v-67906470",
      "path": "/note/ES6/es6%E8%A7%A3%E6%9E%84%E8%B5%8B%E5%80%BC.html",
      "headers": [
        {
          "level": 2,
          "title": "解构赋值",
          "slug": "解构赋值"
        }
      ]
    },
    {
      "title": "Generator",
      "frontmatter": {},
      "regularPath": "/note/ES6/generator%E5%87%BD%E6%95%B0.html",
      "relativePath": "note/ES6/generator函数.md",
      "key": "v-3e9c8daa",
      "path": "/note/ES6/generator%E5%87%BD%E6%95%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "一、相关概念",
          "slug": "一、相关概念"
        },
        {
          "level": 3,
          "title": "1.1.引入的原因",
          "slug": "_1-1-引入的原因"
        },
        {
          "level": 3,
          "title": "1.2.概念",
          "slug": "_1-2-概念"
        },
        {
          "level": 2,
          "title": "二、消息传递",
          "slug": "二、消息传递"
        },
        {
          "level": 2,
          "title": "三、应用",
          "slug": "三、应用"
        },
        {
          "level": 3,
          "title": "3.1同步化表达",
          "slug": "_3-1同步化表达"
        },
        {
          "level": 3,
          "title": "3.2.流程控制中的应用",
          "slug": "_3-2-流程控制中的应用"
        },
        {
          "level": 3,
          "title": "3.4.Generator+Promise",
          "slug": "_3-4-generator-promise"
        },
        {
          "level": 2,
          "title": "五.async和await",
          "slug": "五-async和await"
        },
        {
          "level": 2,
          "title": "六.yield* 委托",
          "slug": "六-yield-委托"
        }
      ]
    },
    {
      "title": "es6函数-箭头函数",
      "frontmatter": {},
      "regularPath": "/note/ES6/es6%E7%AE%AD%E5%A4%B4%E5%87%BD%E6%95%B0.html",
      "relativePath": "note/ES6/es6箭头函数.md",
      "key": "v-1147e8bb",
      "path": "/note/ES6/es6%E7%AE%AD%E5%A4%B4%E5%87%BD%E6%95%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "es6函数-箭头函数",
          "slug": "es6函数-箭头函数"
        },
        {
          "level": 3,
          "title": "一、写法",
          "slug": "一、写法"
        },
        {
          "level": 3,
          "title": "二、特点",
          "slug": "二、特点"
        }
      ]
    },
    {
      "title": "兼容性",
      "frontmatter": {},
      "regularPath": "/note/ES6/%E5%85%BC%E5%AE%B9%E6%80%A7.html",
      "relativePath": "note/ES6/兼容性.md",
      "key": "v-2bf7c978",
      "path": "/note/ES6/%E5%85%BC%E5%AE%B9%E6%80%A7.html",
      "headers": [
        {
          "level": 2,
          "title": "兼容性",
          "slug": "兼容性"
        }
      ]
    },
    {
      "title": "2.1 同步与异步",
      "frontmatter": {},
      "regularPath": "/note/ES6/%E5%90%8C%E6%AD%A5%E5%92%8C%E5%BC%82%E6%AD%A5.html",
      "relativePath": "note/ES6/同步和异步.md",
      "key": "v-a023e40a",
      "path": "/note/ES6/%E5%90%8C%E6%AD%A5%E5%92%8C%E5%BC%82%E6%AD%A5.html",
      "headers": [
        {
          "level": 2,
          "title": "2.1 同步与异步",
          "slug": "_2-1-同步与异步"
        },
        {
          "level": 3,
          "title": "2.1.1 同步",
          "slug": "_2-1-1-同步"
        },
        {
          "level": 3,
          "title": "2.1.2 异步",
          "slug": "_2-1-2-异步"
        },
        {
          "level": 3,
          "title": "2.1.3 回调函数",
          "slug": "_2-1-3-回调函数"
        },
        {
          "level": 2,
          "title": "2.2 为什么使用Promise",
          "slug": "_2-2-为什么使用promise"
        }
      ]
    },
    {
      "title": "前端模块化",
      "frontmatter": {},
      "regularPath": "/note/ES6/%E5%89%8D%E7%AB%AF%E6%A8%A1%E5%9D%97%E5%8C%96.html",
      "relativePath": "note/ES6/前端模块化.md",
      "key": "v-3964a53c",
      "path": "/note/ES6/%E5%89%8D%E7%AB%AF%E6%A8%A1%E5%9D%97%E5%8C%96.html",
      "headers": [
        {
          "level": 2,
          "title": "一、为什么要使用模块化",
          "slug": "一、为什么要使用模块化"
        },
        {
          "level": 2,
          "title": "二、匿名函数模块化",
          "slug": "二、匿名函数模块化"
        },
        {
          "level": 2,
          "title": "三、es6模块化",
          "slug": "三、es6模块化"
        },
        {
          "level": 3,
          "title": "3.1.export",
          "slug": "_3-1-export"
        },
        {
          "level": 3,
          "title": "3.2.default export",
          "slug": "_3-2-default-export"
        },
        {
          "level": 3,
          "title": "3.3.重命名export和import",
          "slug": "_3-3-重命名export和import"
        },
        {
          "level": 2,
          "title": "四、CommonJS",
          "slug": "四、commonjs"
        }
      ]
    },
    {
      "title": "audio",
      "frontmatter": {
        "title": "audio",
        "tags": [
          "HTML"
        ],
        "categories": [
          "HTML"
        ]
      },
      "regularPath": "/note/HTML/audio%E6%A0%87%E7%AD%BE%E5%B8%B8%E7%94%A8api.html",
      "relativePath": "note/HTML/audio标签常用api.md",
      "key": "v-140730de",
      "path": "/note/HTML/audio%E6%A0%87%E7%AD%BE%E5%B8%B8%E7%94%A8api.html",
      "headers": [
        {
          "level": 3,
          "title": "audio常用属性",
          "slug": "audio常用属性"
        },
        {
          "level": 3,
          "title": "audio音乐格式的支持",
          "slug": "audio音乐格式的支持"
        },
        {
          "level": 3,
          "title": "audio属性",
          "slug": "audio属性"
        },
        {
          "level": 3,
          "title": "常用audio的事件：",
          "slug": "常用audio的事件"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "canvas",
      "frontmatter": {
        "title": "canvas",
        "tags": [
          "HTML",
          "HTML5"
        ],
        "categories": [
          "HTML"
        ]
      },
      "regularPath": "/note/HTML/canvas.html",
      "relativePath": "note/HTML/canvas.md",
      "key": "v-daeef31a",
      "path": "/note/HTML/canvas.html",
      "headers": [
        {
          "level": 3,
          "title": "canvas在标签中设置高，与再style中设置宽高有什么区别",
          "slug": "canvas在标签中设置高-与再style中设置宽高有什么区别"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "H5新特性",
      "frontmatter": {
        "title": "H5新特性",
        "tags": [
          "HTML",
          "HTML5"
        ],
        "categories": [
          "HTML"
        ]
      },
      "regularPath": "/note/HTML/h5%E6%96%B0%E7%89%B9%E6%80%A7.html",
      "relativePath": "note/HTML/h5新特性.md",
      "key": "v-1e565195",
      "path": "/note/HTML/h5%E6%96%B0%E7%89%B9%E6%80%A7.html",
      "headers": [
        {
          "level": 3,
          "title": "1、新增选择器",
          "slug": "_1、新增选择器"
        },
        {
          "level": 3,
          "title": "2、拖拽释放 API",
          "slug": "_2、拖拽释放-api"
        },
        {
          "level": 3,
          "title": "3、媒体播放器 video 和 audio",
          "slug": "_3、媒体播放器-video-和-audio"
        },
        {
          "level": 3,
          "title": "4、本地存储 localStorage 和 sessionStorage",
          "slug": "_4、本地存储-localstorage-和-sessionstorage"
        },
        {
          "level": 3,
          "title": "5、离线应用 manifest",
          "slug": "_5、离线应用-manifest"
        },
        {
          "level": 3,
          "title": "6、桌面通知 Notifications",
          "slug": "_6、桌面通知-notifications"
        },
        {
          "level": 3,
          "title": "7、语义化标签",
          "slug": "_7、语义化标签"
        },
        {
          "level": 3,
          "title": "8、增强表单控制 calendar、date、time、email、url、search",
          "slug": "_8、增强表单控制-calendar、date、time、email、url、search"
        },
        {
          "level": 3,
          "title": "9、地理定位",
          "slug": "_9、地理定位"
        },
        {
          "level": 3,
          "title": "10、多任务 webworker",
          "slug": "_10、多任务-webworker"
        },
        {
          "level": 3,
          "title": "11、全双工通讯协议 websocket",
          "slug": "_11、全双工通讯协议-websocket"
        },
        {
          "level": 3,
          "title": "12、历史管理 history",
          "slug": "_12、历史管理-history"
        },
        {
          "level": 3,
          "title": "13、跨域资源共享(CORS) Access-Control-Allow-Origin",
          "slug": "_13、跨域资源共享-cors-access-control-allow-origin"
        },
        {
          "level": 3,
          "title": "14、页面可见性改变事件 visibilitychange",
          "slug": "_14、页面可见性改变事件-visibilitychange"
        },
        {
          "level": 3,
          "title": "15、跨窗口通讯 PostMessage",
          "slug": "_15、跨窗口通讯-postmessage"
        },
        {
          "level": 3,
          "title": "16、Form Data 对象",
          "slug": "_16、form-data-对象"
        },
        {
          "level": 3,
          "title": "17、绘画 canvas",
          "slug": "_17、绘画-canvas"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "input相关问题",
      "frontmatter": {
        "title": "input相关问题",
        "tags": [
          "HTML"
        ],
        "categories": [
          "HTML"
        ]
      },
      "regularPath": "/note/HTML/input.html",
      "relativePath": "note/HTML/input.md",
      "key": "v-32967ca5",
      "path": "/note/HTML/input.html",
      "headers": [
        {
          "level": 2,
          "title": "00.如何禁止input展示输入历史记录",
          "slug": "_00-如何禁止input展示输入历史记录"
        },
        {
          "level": 2,
          "title": "01.input 指定上传文件类型",
          "slug": "_01-input-指定上传文件类型"
        },
        {
          "level": 2,
          "title": "02.input上传文件可以同时选择多张吗？怎么设置？",
          "slug": "_02-input上传文件可以同时选择多张吗-怎么设置"
        },
        {
          "level": 2,
          "title": "03.使用input标签上传图片时，怎么触发默认拍照功能？",
          "slug": "_03-使用input标签上传图片时-怎么触发默认拍照功能"
        },
        {
          "level": 2,
          "title": "04.label标签的作用",
          "slug": "_04-label标签的作用"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "H5语义化标签",
      "frontmatter": {
        "title": "H5语义化标签",
        "tags": [
          "HTML",
          "HTML5"
        ],
        "categories": [
          "HTML"
        ]
      },
      "regularPath": "/note/HTML/h5%E8%AF%AD%E4%B9%89%E5%8C%96%E6%A0%87%E7%AD%BE.html",
      "relativePath": "note/HTML/h5语义化标签.md",
      "key": "v-3cdbaef4",
      "path": "/note/HTML/h5%E8%AF%AD%E4%B9%89%E5%8C%96%E6%A0%87%E7%AD%BE.html",
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "video",
      "frontmatter": {
        "title": "video",
        "tags": [
          "HTML",
          "HTML5"
        ],
        "categories": [
          "HTML"
        ]
      },
      "regularPath": "/note/HTML/video.html",
      "relativePath": "note/HTML/video.md",
      "key": "v-fbb1ff76",
      "path": "/note/HTML/video.html",
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "script",
      "frontmatter": {
        "title": "script",
        "tags": [
          "HTML"
        ],
        "categories": [
          "HTML"
        ]
      },
      "regularPath": "/note/HTML/script.html",
      "relativePath": "note/HTML/script.md",
      "key": "v-075cb6cd",
      "path": "/note/HTML/script.html",
      "headers": [
        {
          "level": 2,
          "title": "01.script 标签为什么建议放在body标签的底部",
          "slug": "_01-script-标签为什么建议放在body标签的底部"
        },
        {
          "level": 3,
          "title": "02.script 标签中 defer 和 async 的区别？",
          "slug": "_02-script-标签中-defer-和-async-的区别"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "meta",
      "frontmatter": {
        "title": "meta",
        "tags": [
          "HTML"
        ],
        "categories": [
          "HTML"
        ]
      },
      "regularPath": "/note/HTML/meta.html",
      "relativePath": "note/HTML/meta.md",
      "key": "v-549cc44e",
      "path": "/note/HTML/meta.html",
      "headers": [
        {
          "level": 2,
          "title": "01.meta viewport 相关",
          "slug": "_01-meta-viewport-相关"
        },
        {
          "level": 2,
          "title": "02.常用的meta元素有哪些",
          "slug": "_02-常用的meta元素有哪些"
        },
        {
          "level": 2,
          "title": "charset",
          "slug": "charset"
        },
        {
          "level": 3,
          "title": "name&content",
          "slug": "name-content"
        },
        {
          "level": 3,
          "title": "http-equiv&content",
          "slug": "http-equiv-content"
        },
        {
          "level": 3,
          "title": "property&content",
          "slug": "property-content"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "为什么会利用多个域名来存储网站资源更有效？",
      "frontmatter": {
        "title": "为什么会利用多个域名来存储网站资源更有效？",
        "tags": [
          "HTML"
        ],
        "categories": [
          "HTML"
        ]
      },
      "regularPath": "/note/HTML/%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E5%88%A9%E7%94%A8%E5%A4%9A%E4%B8%AA%E5%9F%9F%E5%90%8D%E6%9D%A5%E5%AD%98%E5%82%A8%E7%BD%91%E7%AB%99%E8%B5%84%E6%BA%90%E6%9B%B4%E6%9C%89%E6%95%88%EF%BC%9F.html",
      "relativePath": "note/HTML/为什么会利用多个域名来存储网站资源更有效？.md",
      "key": "v-22dbdfb6",
      "path": "/note/HTML/%E4%B8%BA%E4%BB%80%E4%B9%88%E4%BC%9A%E5%88%A9%E7%94%A8%E5%A4%9A%E4%B8%AA%E5%9F%9F%E5%90%8D%E6%9D%A5%E5%AD%98%E5%82%A8%E7%BD%91%E7%AB%99%E8%B5%84%E6%BA%90%E6%9B%B4%E6%9C%89%E6%95%88%EF%BC%9F.html",
      "headers": [
        {
          "level": 3,
          "title": "1、CDN缓存更方便",
          "slug": "_1、cdn缓存更方便"
        },
        {
          "level": 3,
          "title": "2、突破浏览器并发限制",
          "slug": "_2、突破浏览器并发限制"
        },
        {
          "level": 3,
          "title": "3、节约cookie带宽",
          "slug": "_3、节约cookie带宽"
        },
        {
          "level": 3,
          "title": "4、节约主域名的连接数，优化页面响应速度",
          "slug": "_4、节约主域名的连接数-优化页面响应速度"
        },
        {
          "level": 3,
          "title": "5、防止不必要的安全问题",
          "slug": "_5、防止不必要的安全问题"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "其他简答题",
      "frontmatter": {
        "title": "其他简答题",
        "tags": [
          "HTML"
        ],
        "categories": [
          "HTML"
        ]
      },
      "regularPath": "/note/HTML/%E5%85%B6%E4%BB%96%E7%AE%80%E7%AD%94%E9%A2%98.html",
      "relativePath": "note/HTML/其他简答题.md",
      "key": "v-61c0020b",
      "path": "/note/HTML/%E5%85%B6%E4%BB%96%E7%AE%80%E7%AD%94%E9%A2%98.html",
      "headers": [
        {
          "level": 2,
          "title": "01.简述一下src与href的区别",
          "slug": "_01-简述一下src与href的区别"
        },
        {
          "level": 2,
          "title": "02.如何禁止a标签跳转页面或者定位链接？",
          "slug": "_02-如何禁止a标签跳转页面或者定位链接"
        },
        {
          "level": 2,
          "title": "03.html 和css中图片加载与渲染规则是什么样的？",
          "slug": "_03-html-和css中图片加载与渲染规则是什么样的"
        },
        {
          "level": 2,
          "title": "04.什么是渐进增强和优雅降级？",
          "slug": "_04-什么是渐进增强和优雅降级"
        },
        {
          "level": 2,
          "title": "05.Js 动画与 CSS 动画区别及相应实现",
          "slug": "_05-js-动画与-css-动画区别及相应实现"
        },
        {
          "level": 2,
          "title": "06.列出常见的行内元素、块级元素、空(void)元素？",
          "slug": "_06-列出常见的行内元素、块级元素、空-void-元素"
        },
        {
          "level": 2,
          "title": "style 标签写在 body 后与 body 前有什么区别？",
          "slug": "style-标签写在-body-后与-body-前有什么区别"
        },
        {
          "level": 2,
          "title": "什么是DOM和BOM？",
          "slug": "什么是dom和bom"
        },
        {
          "level": 2,
          "title": "Canvas和SVG的区别",
          "slug": "canvas和svg的区别"
        },
        {
          "level": 2,
          "title": "iframe的优点、缺点",
          "slug": "iframe的优点、缺点"
        },
        {
          "level": 2,
          "title": "Doctype 作用？严格模式与混杂模式如何区分？它们有何意义？",
          "slug": "doctype-作用-严格模式与混杂模式如何区分-它们有何意义"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "图片",
      "frontmatter": {
        "title": "图片",
        "tags": [
          "HTML"
        ],
        "categories": [
          "HTML"
        ]
      },
      "regularPath": "/note/HTML/%E5%9B%BE%E7%89%87.html",
      "relativePath": "note/HTML/图片.md",
      "key": "v-4bc1ce98",
      "path": "/note/HTML/%E5%9B%BE%E7%89%87.html",
      "headers": [
        {
          "level": 2,
          "title": "知道的网页制作会用到的图片格式有哪些",
          "slug": "知道的网页制作会用到的图片格式有哪些"
        },
        {
          "level": 2,
          "title": "前端该如何选择图片的格式？",
          "slug": "前端该如何选择图片的格式"
        },
        {
          "level": 3,
          "title": "位图、矢量图",
          "slug": "位图、矢量图"
        },
        {
          "level": 3,
          "title": "图片的压缩类型",
          "slug": "图片的压缩类型"
        },
        {
          "level": 3,
          "title": "图片位数",
          "slug": "图片位数"
        },
        {
          "level": 3,
          "title": "常见的图片的格式",
          "slug": "常见的图片的格式"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "如何实现浏览器内多个标签也之间的通信",
      "frontmatter": {
        "title": "如何实现浏览器内多个标签也之间的通信",
        "tags": [
          "HTML"
        ],
        "categories": [
          "HTML"
        ]
      },
      "regularPath": "/note/HTML/%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0%E6%B5%8F%E8%A7%88%E5%99%A8%E5%86%85%E5%A4%9A%E4%B8%AA%E6%A0%87%E7%AD%BE%E4%B9%9F%E4%B9%8B%E9%97%B4%E7%9A%84%E9%80%9A%E4%BF%A1.html",
      "relativePath": "note/HTML/如何实现浏览器内多个标签也之间的通信.md",
      "key": "v-5c4a2edf",
      "path": "/note/HTML/%E5%A6%82%E4%BD%95%E5%AE%9E%E7%8E%B0%E6%B5%8F%E8%A7%88%E5%99%A8%E5%86%85%E5%A4%9A%E4%B8%AA%E6%A0%87%E7%AD%BE%E4%B9%9F%E4%B9%8B%E9%97%B4%E7%9A%84%E9%80%9A%E4%BF%A1.html",
      "headers": [
        {
          "level": 3,
          "title": "localStorage",
          "slug": "localstorage"
        },
        {
          "level": 3,
          "title": "SharedWorker",
          "slug": "sharedworker"
        },
        {
          "level": 3,
          "title": "WebSocket 通讯",
          "slug": "websocket-通讯"
        },
        {
          "level": 3,
          "title": "定时器 setlnterval + cookie",
          "slug": "定时器-setlnterval-cookie"
        },
        {
          "level": 3,
          "title": "postMessage",
          "slug": "postmessage"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "JS中的offsetWidth、offsetHeight、clientWidth、clientHeight等等的详细介绍",
      "frontmatter": {
        "title": "JS中的offsetWidth、offsetHeight、clientWidth、clientHeight等等的详细介绍",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/JS%E4%B8%AD%E7%9A%84offsetWidth%E3%80%81offsetHeight%E3%80%81clientWidth%E3%80%81clientHeight%E7%AD%89%E7%AD%89%E7%9A%84%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.html",
      "relativePath": "note/JavaScript/JS中的offsetWidth、offsetHeight、clientWidth、clientHeight等等的详细介绍.md",
      "key": "v-32c96274",
      "path": "/note/JavaScript/JS%E4%B8%AD%E7%9A%84offsetWidth%E3%80%81offsetHeight%E3%80%81clientWidth%E3%80%81clientHeight%E7%AD%89%E7%AD%89%E7%9A%84%E8%AF%A6%E7%BB%86%E4%BB%8B%E7%BB%8D.html"
    },
    {
      "title": "call()、apply()、bind()",
      "frontmatter": {
        "title": "call()、apply()、bind()",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/call()%E3%80%81apply()%E3%80%81bind().html",
      "relativePath": "note/JavaScript/call()、apply()、bind().md",
      "key": "v-27b2f202",
      "path": "/note/JavaScript/call()%E3%80%81apply()%E3%80%81bind().html"
    },
    {
      "title": "内置对象",
      "frontmatter": {
        "title": "内置对象",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/js%E5%86%85%E7%BD%AE%E5%AF%B9%E8%B1%A1.html",
      "relativePath": "note/JavaScript/js内置对象.md",
      "key": "v-a58dcba6",
      "path": "/note/JavaScript/js%E5%86%85%E7%BD%AE%E5%AF%B9%E8%B1%A1.html",
      "headers": [
        {
          "level": 3,
          "title": "Math对象",
          "slug": "math对象"
        },
        {
          "level": 3,
          "title": "Date对象",
          "slug": "date对象"
        },
        {
          "level": 3,
          "title": "Array对象",
          "slug": "array对象"
        },
        {
          "level": 3,
          "title": "正则表达式对象",
          "slug": "正则表达式对象"
        },
        {
          "level": 3,
          "title": "String对象",
          "slug": "string对象"
        }
      ]
    },
    {
      "title": "函数",
      "frontmatter": {
        "title": "函数",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/js%E5%87%BD%E6%95%B0.html",
      "relativePath": "note/JavaScript/js函数.md",
      "key": "v-e313921c",
      "path": "/note/JavaScript/js%E5%87%BD%E6%95%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "一、定义方式",
          "slug": "一、定义方式"
        },
        {
          "level": 2,
          "title": "二、函数调用",
          "slug": "二、函数调用"
        },
        {
          "level": 3,
          "title": "2.1.调用方式",
          "slug": "_2-1-调用方式"
        },
        {
          "level": 3,
          "title": "2.2.this 指向",
          "slug": "_2-2-this-指向"
        },
        {
          "level": 3,
          "title": "2.3.call、apply、bind",
          "slug": "_2-3-call、apply、bind"
        },
        {
          "level": 2,
          "title": "三、函数成员",
          "slug": "三、函数成员"
        },
        {
          "level": 2,
          "title": "四、函数闭包",
          "slug": "四、函数闭包"
        },
        {
          "level": 3,
          "title": "4.1.匿名函数",
          "slug": "_4-1-匿名函数"
        },
        {
          "level": 3,
          "title": "4.2.概念",
          "slug": "_4-2-概念"
        },
        {
          "level": 3,
          "title": "4.3.特点",
          "slug": "_4-3-特点"
        },
        {
          "level": 2,
          "title": "五、函数递归",
          "slug": "五、函数递归"
        },
        {
          "level": 2,
          "title": "六、重载和重写",
          "slug": "六、重载和重写"
        }
      ]
    },
    {
      "title": "面向对象",
      "frontmatter": {
        "title": "面向对象",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/js%E5%8E%9F%E5%9E%8B.html",
      "relativePath": "note/JavaScript/js原型.md",
      "key": "v-35a4858b",
      "path": "/note/JavaScript/js%E5%8E%9F%E5%9E%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "一、概念",
          "slug": "一、概念"
        },
        {
          "level": 2,
          "title": "二、创建对象方式",
          "slug": "二、创建对象方式"
        },
        {
          "level": 2,
          "title": "三、操作对象",
          "slug": "三、操作对象"
        },
        {
          "level": 2,
          "title": "四、构造函数",
          "slug": "四、构造函数"
        },
        {
          "level": 3,
          "title": "4.1.new关键字",
          "slug": "_4-1-new关键字"
        },
        {
          "level": 3,
          "title": "4.2.和实例对象的关系",
          "slug": "_4-2-和实例对象的关系"
        },
        {
          "level": 3,
          "title": "4.3.问题",
          "slug": "_4-3-问题"
        },
        {
          "level": 2,
          "title": "五、原型",
          "slug": "五、原型"
        },
        {
          "level": 3,
          "title": "5.1.prototype",
          "slug": "_5-1-prototype"
        },
        {
          "level": 3,
          "title": "5.2.构造函数、实例、原型三者之间的关系",
          "slug": "_5-2-构造函数、实例、原型三者之间的关系"
        },
        {
          "level": 3,
          "title": "5.3.原型链",
          "slug": "_5-3-原型链"
        },
        {
          "level": 3,
          "title": "5.4.原型语法",
          "slug": "_5-4-原型语法"
        },
        {
          "level": 3,
          "title": "5.5.使用建议",
          "slug": "_5-5-使用建议"
        },
        {
          "level": 2,
          "title": "六、继承",
          "slug": "六、继承"
        },
        {
          "level": 3,
          "title": "6.1.原型继承",
          "slug": "_6-1-原型继承"
        },
        {
          "level": 3,
          "title": "6.2.借用构造函数",
          "slug": "_6-2-借用构造函数"
        },
        {
          "level": 3,
          "title": "6.3.组合继承",
          "slug": "_6-3-组合继承"
        },
        {
          "level": 3,
          "title": "6.4.拷贝继承",
          "slug": "_6-4-拷贝继承"
        },
        {
          "level": 2,
          "title": "七、Objece",
          "slug": "七、objece"
        },
        {
          "level": 3,
          "title": "静态成员",
          "slug": "静态成员"
        },
        {
          "level": 3,
          "title": "实例成员",
          "slug": "实例成员"
        }
      ]
    },
    {
      "title": "String对象的常用方法",
      "frontmatter": {
        "title": "String对象的常用方法",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/js%E5%AD%97%E7%AC%A6%E4%B8%B2.html",
      "relativePath": "note/JavaScript/js字符串.md",
      "key": "v-c74fcb98",
      "path": "/note/JavaScript/js%E5%AD%97%E7%AC%A6%E4%B8%B2.html",
      "headers": [
        {
          "level": 2,
          "title": "一、字符方法",
          "slug": "一、字符方法"
        },
        {
          "level": 3,
          "title": "charAt()",
          "slug": "charat"
        },
        {
          "level": 3,
          "title": "charCodeAt()",
          "slug": "charcodeat"
        },
        {
          "level": 3,
          "title": "str[i]",
          "slug": "str-i"
        },
        {
          "level": 2,
          "title": "二、字符串操作方法",
          "slug": "二、字符串操作方法"
        },
        {
          "level": 3,
          "title": "concat()",
          "slug": "concat"
        },
        {
          "level": 3,
          "title": "slice()",
          "slug": "slice"
        },
        {
          "level": 3,
          "title": "substring()",
          "slug": "substring"
        },
        {
          "level": 3,
          "title": "substr()",
          "slug": "substr"
        },
        {
          "level": 2,
          "title": "三、位置方法",
          "slug": "三、位置方法"
        },
        {
          "level": 3,
          "title": "indexOf()、lastIndexOf()",
          "slug": "indexof-、lastindexof"
        },
        {
          "level": 3,
          "title": "search()",
          "slug": "search"
        },
        {
          "level": 3,
          "title": "match()",
          "slug": "match"
        },
        {
          "level": 2,
          "title": "四、去除空白",
          "slug": "四、去除空白"
        },
        {
          "level": 3,
          "title": "trim()",
          "slug": "trim"
        },
        {
          "level": 2,
          "title": "五、大小写转换方法",
          "slug": "五、大小写转换方法"
        },
        {
          "level": 3,
          "title": "to(Locale)UpperCase()",
          "slug": "to-locale-uppercase"
        },
        {
          "level": 3,
          "title": "to(Locale)LowerCase()",
          "slug": "to-locale-lowercase"
        },
        {
          "level": 2,
          "title": "六、其他方法",
          "slug": "六、其他方法"
        },
        {
          "level": 3,
          "title": "replace()",
          "slug": "replace"
        },
        {
          "level": 3,
          "title": "split()",
          "slug": "split"
        },
        {
          "level": 3,
          "title": "fromCharCode()",
          "slug": "fromcharcode"
        },
        {
          "level": 2,
          "title": "七、ES6新增",
          "slug": "七、es6新增"
        },
        {
          "level": 3,
          "title": "子字符串的识别",
          "slug": "子字符串的识别"
        },
        {
          "level": 3,
          "title": "字符串重复",
          "slug": "字符串重复"
        },
        {
          "level": 3,
          "title": "字符串补全",
          "slug": "字符串补全"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/note/JavaScript/js%E6%89%A7%E8%A1%8C%E8%BF%87%E7%A8%8B.html",
      "relativePath": "note/JavaScript/js执行过程.md",
      "key": "v-00e2c9cd",
      "path": "/note/JavaScript/js%E6%89%A7%E8%A1%8C%E8%BF%87%E7%A8%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "一、作用域",
          "slug": "一、作用域"
        },
        {
          "level": 3,
          "title": "词法作用域",
          "slug": "词法作用域"
        },
        {
          "level": 2,
          "title": "二、预解析",
          "slug": "二、预解析"
        },
        {
          "level": 2,
          "title": "三、执行",
          "slug": "三、执行"
        }
      ]
    },
    {
      "title": "JS中的数据类型",
      "frontmatter": {
        "title": "JS中的数据类型",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/js%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B.html",
      "relativePath": "note/JavaScript/js数据类型.md",
      "key": "v-b16f5d54",
      "path": "/note/JavaScript/js%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "一、JS中的数据类型",
          "slug": "一、js中的数据类型"
        },
        {
          "level": 3,
          "title": "1.1.基本类型（值类型）",
          "slug": "_1-1-基本类型-值类型"
        },
        {
          "level": 3,
          "title": "1.2.复杂类型（引用类型）",
          "slug": "_1-2-复杂类型-引用类型"
        },
        {
          "level": 3,
          "title": "1.3.堆和栈",
          "slug": "_1-3-堆和栈"
        },
        {
          "level": 2,
          "title": "二、JS类型检测方式",
          "slug": "二、js类型检测方式"
        },
        {
          "level": 3,
          "title": "2.1.typeof：主要用于检测基本类型",
          "slug": "_2-1-typeof-主要用于检测基本类型"
        },
        {
          "level": 3,
          "title": "2.2.instanceof：主要用于检测引用类型",
          "slug": "_2-2-instanceof-主要用于检测引用类型"
        },
        {
          "level": 3,
          "title": "2.3.Object.prototype.toString.call()：",
          "slug": "_2-3-object-prototype-tostring-call"
        },
        {
          "level": 2,
          "title": "三、值类型和引用类型在内存中的存储方式",
          "slug": "三、值类型和引用类型在内存中的存储方式"
        },
        {
          "level": 2,
          "title": "四、值类型复制和引用类型复制",
          "slug": "四、值类型复制和引用类型复制"
        },
        {
          "level": 3,
          "title": "4.1.深拷贝和浅拷贝",
          "slug": "_4-1-深拷贝和浅拷贝"
        },
        {
          "level": 2,
          "title": "五、值类型和引用类型参数传递",
          "slug": "五、值类型和引用类型参数传递"
        },
        {
          "level": 2,
          "title": "六、值类型与引用类型的差别",
          "slug": "六、值类型与引用类型的差别"
        },
        {
          "level": 2,
          "title": "七、数据类型转换",
          "slug": "七、数据类型转换"
        },
        {
          "level": 3,
          "title": "7.1.转换成字符串类型",
          "slug": "_7-1-转换成字符串类型"
        },
        {
          "level": 3,
          "title": "7.2.转换成数值类型",
          "slug": "_7-2-转换成数值类型"
        },
        {
          "level": 3,
          "title": "7.3.转换成布尔类型",
          "slug": "_7-3-转换成布尔类型"
        }
      ]
    },
    {
      "title": "JS中的数据类型2",
      "frontmatter": {
        "title": "JS中的数据类型2",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/js%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B2.html",
      "relativePath": "note/JavaScript/js数据类型2.md",
      "key": "v-232abf48",
      "path": "/note/JavaScript/js%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B2.html",
      "headers": [
        {
          "level": 2,
          "title": "JavaScript属于什么类型的语言?",
          "slug": "javascript属于什么类型的语言"
        }
      ]
    },
    {
      "title": "dpr、设备像素、CSS像素",
      "frontmatter": {
        "title": "dpr、设备像素、CSS像素",
        "tags": [
          "HTML"
        ],
        "categories": [
          "HTML"
        ]
      },
      "regularPath": "/note/HTML/dpr%E3%80%81%E8%AE%BE%E5%A4%87%E5%83%8F%E7%B4%A0%E3%80%81CSS%E5%83%8F%E7%B4%A0.html",
      "relativePath": "note/HTML/dpr、设备像素、CSS像素.md",
      "key": "v-057a5a9c",
      "path": "/note/HTML/dpr%E3%80%81%E8%AE%BE%E5%A4%87%E5%83%8F%E7%B4%A0%E3%80%81CSS%E5%83%8F%E7%B4%A0.html",
      "headers": [
        {
          "level": 3,
          "title": "一台设备的dpr，是否会可变？",
          "slug": "一台设备的dpr-是否会可变"
        }
      ],
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "正则",
      "frontmatter": {
        "title": "正则",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/js%E6%AD%A3%E5%88%99.html",
      "relativePath": "note/JavaScript/js正则.md",
      "key": "v-7caad962",
      "path": "/note/JavaScript/js%E6%AD%A3%E5%88%99.html",
      "headers": [
        {
          "level": 2,
          "title": "一、正则表达式",
          "slug": "一、正则表达式"
        },
        {
          "level": 3,
          "title": "1.1.元字符串",
          "slug": "_1-1-元字符串"
        },
        {
          "level": 3,
          "title": "2.2.案例",
          "slug": "_2-2-案例"
        },
        {
          "level": 2,
          "title": "二、JS 中使用正则表达式",
          "slug": "二、js-中使用正则表达式"
        },
        {
          "level": 3,
          "title": "2.1.创建正则对象",
          "slug": "_2-1-创建正则对象"
        },
        {
          "level": 3,
          "title": "2.2.方法",
          "slug": "_2-2-方法"
        },
        {
          "level": 2,
          "title": "三、案例：表单验证",
          "slug": "三、案例-表单验证"
        }
      ]
    },
    {
      "title": "Array对象的常用方法",
      "frontmatter": {
        "title": "Array对象的常用方法",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/js%E6%95%B0%E7%BB%84.html",
      "relativePath": "note/JavaScript/js数组.md",
      "key": "v-54cbd2b6",
      "path": "/note/JavaScript/js%E6%95%B0%E7%BB%84.html",
      "headers": [
        {
          "level": 2,
          "title": "一、检验数组",
          "slug": "一、检验数组"
        },
        {
          "level": 3,
          "title": "instanceof",
          "slug": "instanceof"
        },
        {
          "level": 3,
          "title": "Object.prototype.toString.call()",
          "slug": "object-prototype-tostring-call"
        },
        {
          "level": 3,
          "title": "Array.isArray(arr)",
          "slug": "array-isarray-arr"
        },
        {
          "level": 2,
          "title": "二、转换方法",
          "slug": "二、转换方法"
        },
        {
          "level": 3,
          "title": "toString()",
          "slug": "tostring"
        },
        {
          "level": 3,
          "title": "valueOf()",
          "slug": "valueof"
        },
        {
          "level": 3,
          "title": "join()",
          "slug": "join"
        },
        {
          "level": 3,
          "title": "Array.from()",
          "slug": "array-from"
        },
        {
          "level": 2,
          "title": "三、栈方法",
          "slug": "三、栈方法"
        },
        {
          "level": 3,
          "title": "push()、pop()",
          "slug": "push-、pop"
        },
        {
          "level": 2,
          "title": "四、队列方法",
          "slug": "四、队列方法"
        },
        {
          "level": 3,
          "title": "unshift()、shift()",
          "slug": "unshift-、shift"
        },
        {
          "level": 2,
          "title": "五、排序方法",
          "slug": "五、排序方法"
        },
        {
          "level": 3,
          "title": "reverse()",
          "slug": "reverse"
        },
        {
          "level": 3,
          "title": "sort()",
          "slug": "sort"
        },
        {
          "level": 2,
          "title": "六、操作方法",
          "slug": "六、操作方法"
        },
        {
          "level": 3,
          "title": "concat()",
          "slug": "concat"
        },
        {
          "level": 3,
          "title": "slice()",
          "slug": "slice"
        },
        {
          "level": 3,
          "title": "splice()",
          "slug": "splice"
        },
        {
          "level": 2,
          "title": "七、位置方法",
          "slug": "七、位置方法"
        },
        {
          "level": 3,
          "title": "indexOf()、lastIndexOf()",
          "slug": "indexof-、lastindexof"
        },
        {
          "level": 2,
          "title": "八、迭代方法",
          "slug": "八、迭代方法"
        },
        {
          "level": 3,
          "title": "map()",
          "slug": "map"
        },
        {
          "level": 3,
          "title": "redece()",
          "slug": "redece"
        },
        {
          "level": 3,
          "title": "filter()",
          "slug": "filter"
        },
        {
          "level": 3,
          "title": "every()",
          "slug": "every"
        },
        {
          "level": 3,
          "title": "some()",
          "slug": "some"
        },
        {
          "level": 3,
          "title": "forEach()",
          "slug": "foreach"
        },
        {
          "level": 3,
          "title": "find()",
          "slug": "find"
        },
        {
          "level": 3,
          "title": "findIndex()",
          "slug": "findindex"
        },
        {
          "level": 2,
          "title": "九、清空数组",
          "slug": "九、清空数组"
        },
        {
          "level": 2,
          "title": "十、新增方法",
          "slug": "十、新增方法"
        }
      ]
    },
    {
      "title": "jQuery",
      "frontmatter": {
        "title": "jQuery",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/jquery%E5%B0%8F%E7%AC%94%E8%AE%B0.html",
      "relativePath": "note/JavaScript/jquery小笔记.md",
      "key": "v-9925e42e",
      "path": "/note/JavaScript/jquery%E5%B0%8F%E7%AC%94%E8%AE%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "文档就绪函数",
          "slug": "文档就绪函数"
        },
        {
          "level": 3,
          "title": "trigger() 方法",
          "slug": "trigger-方法"
        }
      ]
    },
    {
      "title": "JS语句",
      "frontmatter": {
        "title": "JS语句",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/js%E8%AF%AD%E5%8F%A5.html",
      "relativePath": "note/JavaScript/js语句.md",
      "key": "v-19bbd990",
      "path": "/note/JavaScript/js%E8%AF%AD%E5%8F%A5.html",
      "headers": [
        {
          "level": 2,
          "title": "一、分支结构",
          "slug": "一、分支结构"
        },
        {
          "level": 3,
          "title": "1.1.switch语句",
          "slug": "_1-1-switch语句"
        },
        {
          "level": 2,
          "title": "二、循环结构",
          "slug": "二、循环结构"
        },
        {
          "level": 3,
          "title": "2.1.while语句",
          "slug": "_2-1-while语句"
        },
        {
          "level": 3,
          "title": "2.2.do...while语句",
          "slug": "_2-2-do-while语句"
        },
        {
          "level": 3,
          "title": "2.3.for语句",
          "slug": "_2-3-for语句"
        },
        {
          "level": 3,
          "title": "2.4.continue和break",
          "slug": "_2-4-continue和break"
        }
      ]
    },
    {
      "title": "闭包",
      "frontmatter": {
        "title": "闭包",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/js%E9%97%AD%E5%8C%85.html",
      "relativePath": "note/JavaScript/js闭包.md",
      "key": "v-1c4e1118",
      "path": "/note/JavaScript/js%E9%97%AD%E5%8C%85.html",
      "headers": [
        {
          "level": 2,
          "title": "一、变量的作用域",
          "slug": "一、变量的作用域"
        },
        {
          "level": 2,
          "title": "二、如何从外部读取局部变量？",
          "slug": "二、如何从外部读取局部变量"
        },
        {
          "level": 2,
          "title": "三、闭包的概念",
          "slug": "三、闭包的概念"
        },
        {
          "level": 2,
          "title": "四、闭包的用途",
          "slug": "四、闭包的用途"
        },
        {
          "level": 2,
          "title": "五、闭包的应用",
          "slug": "五、闭包的应用"
        },
        {
          "level": 2,
          "title": "六、使用闭包的注意点",
          "slug": "六、使用闭包的注意点"
        },
        {
          "level": 2,
          "title": "七、总结",
          "slug": "七、总结"
        }
      ]
    },
    {
      "title": "面向对象",
      "frontmatter": {
        "title": "面向对象",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/js%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html",
      "relativePath": "note/JavaScript/js面向对象.md",
      "key": "v-75884935",
      "path": "/note/JavaScript/js%E9%9D%A2%E5%90%91%E5%AF%B9%E8%B1%A1.html",
      "headers": [
        {
          "level": 2,
          "title": "一、概念",
          "slug": "一、概念"
        },
        {
          "level": 2,
          "title": "二、创建对象方式",
          "slug": "二、创建对象方式"
        },
        {
          "level": 2,
          "title": "三、操作对象",
          "slug": "三、操作对象"
        },
        {
          "level": 2,
          "title": "四、构造函数",
          "slug": "四、构造函数"
        },
        {
          "level": 3,
          "title": "4.1.new关键字",
          "slug": "_4-1-new关键字"
        },
        {
          "level": 3,
          "title": "4.2.和实例对象的关系",
          "slug": "_4-2-和实例对象的关系"
        },
        {
          "level": 3,
          "title": "4.3.问题",
          "slug": "_4-3-问题"
        },
        {
          "level": 2,
          "title": "五、原型",
          "slug": "五、原型"
        },
        {
          "level": 3,
          "title": "5.1.prototype",
          "slug": "_5-1-prototype"
        },
        {
          "level": 3,
          "title": "5.2.构造函数、实例、原型三者之间的关系",
          "slug": "_5-2-构造函数、实例、原型三者之间的关系"
        },
        {
          "level": 3,
          "title": "5.3.原型链",
          "slug": "_5-3-原型链"
        },
        {
          "level": 3,
          "title": "5.4.原型语法",
          "slug": "_5-4-原型语法"
        },
        {
          "level": 3,
          "title": "5.5.使用建议",
          "slug": "_5-5-使用建议"
        },
        {
          "level": 2,
          "title": "六、继承",
          "slug": "六、继承"
        },
        {
          "level": 3,
          "title": "6.1.原型继承",
          "slug": "_6-1-原型继承"
        },
        {
          "level": 3,
          "title": "6.2.借用构造函数",
          "slug": "_6-2-借用构造函数"
        },
        {
          "level": 3,
          "title": "6.3.组合继承",
          "slug": "_6-3-组合继承"
        },
        {
          "level": 3,
          "title": "6.4.拷贝继承",
          "slug": "_6-4-拷贝继承"
        },
        {
          "level": 2,
          "title": "七、Objece",
          "slug": "七、objece"
        },
        {
          "level": 3,
          "title": "静态成员",
          "slug": "静态成员"
        },
        {
          "level": 3,
          "title": "实例成员",
          "slug": "实例成员"
        }
      ]
    },
    {
      "title": "内存泄露",
      "frontmatter": {
        "title": "内存泄露",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/%E5%86%85%E5%AD%98%E6%B3%84%E6%BC%8F.html",
      "relativePath": "note/JavaScript/内存泄漏.md",
      "key": "v-bd5ec76c",
      "path": "/note/JavaScript/%E5%86%85%E5%AD%98%E6%B3%84%E6%BC%8F.html",
      "headers": [
        {
          "level": 2,
          "title": "一、4种常见的内存泄露",
          "slug": "一、4种常见的内存泄露"
        },
        {
          "level": 3,
          "title": "1.1.意外的全局变量",
          "slug": "_1-1-意外的全局变量"
        },
        {
          "level": 3,
          "title": "1.2.被遗忘的计时器，或回调函数",
          "slug": "_1-2-被遗忘的计时器-或回调函数"
        },
        {
          "level": 3,
          "title": "1.3.脱离DOM的引用",
          "slug": "_1-3-脱离dom的引用"
        },
        {
          "level": 3,
          "title": "1.4.闭包",
          "slug": "_1-4-闭包"
        },
        {
          "level": 2,
          "title": "二、内存泄漏的识别方法",
          "slug": "二、内存泄漏的识别方法"
        },
        {
          "level": 3,
          "title": "2.1.Chrome浏览器的控制台Performance或Memory",
          "slug": "_2-1-chrome浏览器的控制台performance或memory"
        },
        {
          "level": 3,
          "title": "2.2.Node提供的process.memoryUsage方法",
          "slug": "_2-2-node提供的process-memoryusage方法"
        },
        {
          "level": 2,
          "title": "三、总结",
          "slug": "三、总结"
        },
        {
          "level": 3,
          "title": "3.1.内存泄漏包括：",
          "slug": "_3-1-内存泄漏包括"
        },
        {
          "level": 3,
          "title": "3.2.避免内存泄漏：",
          "slug": "_3-2-避免内存泄漏"
        }
      ]
    },
    {
      "title": "快速排序算法",
      "frontmatter": {
        "title": "快速排序算法",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/%E5%BF%AB%E9%80%9F%E6%8E%92%E5%BA%8F%E7%AE%97%E6%B3%95.html",
      "relativePath": "note/JavaScript/快速排序算法.md",
      "key": "v-09689aec",
      "path": "/note/JavaScript/%E5%BF%AB%E9%80%9F%E6%8E%92%E5%BA%8F%E7%AE%97%E6%B3%95.html"
    },
    {
      "title": "垃圾回收机制(GC)",
      "frontmatter": {
        "title": "垃圾回收机制(GC)",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6%E6%9C%BA%E5%88%B6GC.html",
      "relativePath": "note/JavaScript/垃圾回收机制GC.md",
      "key": "v-21e534be",
      "path": "/note/JavaScript/%E5%9E%83%E5%9C%BE%E5%9B%9E%E6%94%B6%E6%9C%BA%E5%88%B6GC.html",
      "headers": [
        {
          "level": 2,
          "title": "一、垃圾产生&为何回收",
          "slug": "一、垃圾产生-为何回收"
        },
        {
          "level": 2,
          "title": "二、垃圾回收策略",
          "slug": "二、垃圾回收策略"
        },
        {
          "level": 2,
          "title": "三、标记清除算法",
          "slug": "三、标记清除算法"
        },
        {
          "level": 2,
          "title": "四、引用计数算法",
          "slug": "四、引用计数算法"
        },
        {
          "level": 3,
          "title": "循环引用",
          "slug": "循环引用"
        },
        {
          "level": 2,
          "title": "五、V8对GC的优化",
          "slug": "五、v8对gc的优化"
        },
        {
          "level": 3,
          "title": "5.1.分代式垃圾回收",
          "slug": "_5-1-分代式垃圾回收"
        },
        {
          "level": 3,
          "title": "5.2.并行回收(Parallel)",
          "slug": "_5-2-并行回收-parallel"
        },
        {
          "level": 3,
          "title": "5.3.增量标记与懒性清理",
          "slug": "_5-3-增量标记与懒性清理"
        },
        {
          "level": 3,
          "title": "5.4.并发回收",
          "slug": "_5-4-并发回收"
        },
        {
          "level": 3,
          "title": "5.4.再说V8中GC优化",
          "slug": "_5-4-再说v8中gc优化"
        }
      ]
    },
    {
      "title": "数组",
      "frontmatter": {
        "title": "数组",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/%E6%95%B0%E7%BB%84.html",
      "relativePath": "note/JavaScript/数组.md",
      "key": "v-3c54c848",
      "path": "/note/JavaScript/%E6%95%B0%E7%BB%84.html",
      "headers": [
        {
          "level": 2,
          "title": "一、创建数组",
          "slug": "一、创建数组"
        },
        {
          "level": 2,
          "title": "二、数组方法",
          "slug": "二、数组方法"
        }
      ]
    },
    {
      "title": "深拷贝和浅拷贝",
      "frontmatter": {
        "title": "深拷贝和浅拷贝",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/%E6%B7%B1%E6%8B%B7%E8%B4%9D%E5%92%8C%E6%B5%85%E6%8B%B7%E8%B4%9D.html",
      "relativePath": "note/JavaScript/深拷贝和浅拷贝.md",
      "key": "v-3b8007b2",
      "path": "/note/JavaScript/%E6%B7%B1%E6%8B%B7%E8%B4%9D%E5%92%8C%E6%B5%85%E6%8B%B7%E8%B4%9D.html",
      "headers": [
        {
          "level": 3,
          "title": "一、浅拷贝",
          "slug": "一、浅拷贝"
        },
        {
          "level": 3,
          "title": "二、深拷贝",
          "slug": "二、深拷贝"
        }
      ]
    },
    {
      "title": "编程算法",
      "frontmatter": {
        "title": "编程算法",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/%E7%BC%96%E7%A8%8B%E7%AE%97%E6%B3%95.html",
      "relativePath": "note/JavaScript/编程算法.md",
      "key": "v-06c183ed",
      "path": "/note/JavaScript/%E7%BC%96%E7%A8%8B%E7%AE%97%E6%B3%95.html",
      "headers": [
        {
          "level": 2,
          "title": "数组",
          "slug": "数组"
        },
        {
          "level": 3,
          "title": "1、数组去重",
          "slug": "_1、数组去重"
        },
        {
          "level": 3,
          "title": "2、数组交集",
          "slug": "_2、数组交集"
        },
        {
          "level": 3,
          "title": "3、数组并集",
          "slug": "_3、数组并集"
        },
        {
          "level": 3,
          "title": "4、数组差集",
          "slug": "_4、数组差集"
        },
        {
          "level": 2,
          "title": "字符串转换为数组的 4 个方法",
          "slug": "字符串转换为数组的-4-个方法"
        },
        {
          "level": 3,
          "title": "1、split() 方法",
          "slug": "_1、split-方法"
        },
        {
          "level": 3,
          "title": "2、展开运算符",
          "slug": "_2、展开运算符"
        },
        {
          "level": 3,
          "title": "3、解构赋值",
          "slug": "_3、解构赋值"
        },
        {
          "level": 3,
          "title": "4、Array.from",
          "slug": "_4、array-from"
        }
      ]
    },
    {
      "title": "防抖节流",
      "frontmatter": {
        "title": "防抖节流",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/%E9%98%B2%E6%8A%96%E8%8A%82%E6%B5%81.html",
      "relativePath": "note/JavaScript/防抖节流.md",
      "key": "v-18568991",
      "path": "/note/JavaScript/%E9%98%B2%E6%8A%96%E8%8A%82%E6%B5%81.html",
      "headers": [
        {
          "level": 3,
          "title": "一、演示卡顿现象",
          "slug": "一、演示卡顿现象"
        },
        {
          "level": 3,
          "title": "二、防抖",
          "slug": "二、防抖"
        },
        {
          "level": 3,
          "title": "三、节流",
          "slug": "三、节流"
        },
        {
          "level": 3,
          "title": "四、应用场景",
          "slug": "四、应用场景"
        },
        {
          "level": 3,
          "title": "五、总结：",
          "slug": "五、总结"
        },
        {
          "level": 3,
          "title": "六、lodash插件防抖和节流",
          "slug": "六、lodash插件防抖和节流"
        }
      ]
    },
    {
      "title": "解决JavaScript数字精度丢失问题的方法",
      "frontmatter": {
        "title": "解决JavaScript数字精度丢失问题的方法",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/%E8%A7%A3%E5%86%B3JavaScript%E6%95%B0%E5%AD%97%E7%B2%BE%E5%BA%A6%E4%B8%A2%E5%A4%B1%E9%97%AE%E9%A2%98%E7%9A%84%E6%96%B9%E6%B3%95.html",
      "relativePath": "note/JavaScript/解决JavaScript数字精度丢失问题的方法.md",
      "key": "v-5bbaf890",
      "path": "/note/JavaScript/%E8%A7%A3%E5%86%B3JavaScript%E6%95%B0%E5%AD%97%E7%B2%BE%E5%BA%A6%E4%B8%A2%E5%A4%B1%E9%97%AE%E9%A2%98%E7%9A%84%E6%96%B9%E6%B3%95.html",
      "headers": [
        {
          "level": 2,
          "title": "一、JS数字精度丢失的一些典型问题",
          "slug": "一、js数字精度丢失的一些典型问题"
        },
        {
          "level": 2,
          "title": "二、JS 数字丢失精度的原因",
          "slug": "二、js-数字丢失精度的原因"
        },
        {
          "level": 2,
          "title": "三、解决方案",
          "slug": "三、解决方案"
        },
        {
          "level": 2,
          "title": "四、三方库",
          "slug": "四、三方库"
        }
      ]
    },
    {
      "title": "跨域问题",
      "frontmatter": {
        "title": "跨域问题",
        "tags": [
          "JavaScript"
        ],
        "categories": [
          "JavaScript"
        ]
      },
      "regularPath": "/note/JavaScript/%E8%B7%A8%E5%9F%9F%E9%97%AE%E9%A2%98.html",
      "relativePath": "note/JavaScript/跨域问题.md",
      "key": "v-2c49a5e3",
      "path": "/note/JavaScript/%E8%B7%A8%E5%9F%9F%E9%97%AE%E9%A2%98.html"
    },
    {
      "title": "vuepress",
      "frontmatter": {
        "title": "vuepress",
        "tags": [
          "vuepress"
        ],
        "categories": [
          "vuepress"
        ]
      },
      "regularPath": "/note/VuePress/vuepress.html",
      "relativePath": "note/VuePress/vuepress.md",
      "key": "v-bae62ae6",
      "path": "/note/VuePress/vuepress.html",
      "headers": [
        {
          "level": 2,
          "title": "01.基础环境",
          "slug": "_01-基础环境"
        },
        {
          "level": 2,
          "title": "02.初试vuepress",
          "slug": "_02-初试vuepress"
        },
        {
          "level": 2,
          "title": "03.导航栏",
          "slug": "_03-导航栏"
        },
        {
          "level": 2,
          "title": "04.侧边栏",
          "slug": "_04-侧边栏"
        },
        {
          "level": 2,
          "title": "05.SEO",
          "slug": "_05-seo"
        },
        {
          "level": 2,
          "title": "06.更新时间",
          "slug": "_06-更新时间"
        },
        {
          "level": 2,
          "title": "07.发布到github.io",
          "slug": "_07-发布到github-io"
        },
        {
          "level": 2,
          "title": "08.自定域名",
          "slug": "_08-自定域名"
        },
        {
          "level": 2,
          "title": "09.启用PWA",
          "slug": "_09-启用pwa"
        },
        {
          "level": 2,
          "title": "10.vssue评论",
          "slug": "_10-vssue评论"
        },
        {
          "level": 2,
          "title": "14.back to top",
          "slug": "_14-back-to-top"
        },
        {
          "level": 2,
          "title": "12.google analytics",
          "slug": "_12-google-analytics"
        },
        {
          "level": 2,
          "title": "13.分割config",
          "slug": "_13-分割config"
        },
        {
          "level": 2,
          "title": "14.保护隐私",
          "slug": "_14-保护隐私"
        },
        {
          "level": 2,
          "title": "15.Markdown 用法进阶",
          "slug": "_15-markdown-用法进阶"
        },
        {
          "level": 2,
          "title": "16.自动化部署 Travis-CI /github actions",
          "slug": "_16-自动化部署-travis-ci-github-actions"
        },
        {
          "level": 2,
          "title": "17.逼格徽章",
          "slug": "_17-逼格徽章"
        },
        {
          "level": 2,
          "title": "18.图片缩放",
          "slug": "_18-图片缩放"
        },
        {
          "level": 2,
          "title": "19.自动生成侧边栏",
          "slug": "_19-自动生成侧边栏"
        },
        {
          "level": 2,
          "title": "20.algolia 替换默认搜索",
          "slug": "_20-algolia-替换默认搜索"
        }
      ]
    },
    {
      "title": "前端需要注意哪些SEO",
      "frontmatter": {
        "title": "前端需要注意哪些SEO",
        "tags": [
          "HTML"
        ],
        "categories": [
          "HTML"
        ]
      },
      "regularPath": "/note/HTML/%E5%89%8D%E7%AB%AF%E9%9C%80%E8%A6%81%E6%B3%A8%E6%84%8F%E5%93%AA%E4%BA%9BSEO.html",
      "relativePath": "note/HTML/前端需要注意哪些SEO.md",
      "key": "v-435a9109",
      "path": "/note/HTML/%E5%89%8D%E7%AB%AF%E9%9C%80%E8%A6%81%E6%B3%A8%E6%84%8F%E5%93%AA%E4%BA%9BSEO.html",
      "lastUpdated": "2022-05-02 2:11:34",
      "lastUpdatedTimestamp": 1651428694000
    },
    {
      "title": "一、大屏适配方案",
      "frontmatter": {},
      "regularPath": "/note/bi%E5%A4%A7%E5%B1%8F%E5%88%B6%E4%BD%9C/%E5%A4%A7%E5%B1%8F%E9%A1%B9%E7%9B%AE%E5%88%B6%E4%BD%9C%E7%AC%94%E8%AE%B0.html",
      "relativePath": "note/bi大屏制作/大屏项目制作笔记.md",
      "key": "v-9b6ec534",
      "path": "/note/bi%E5%A4%A7%E5%B1%8F%E5%88%B6%E4%BD%9C/%E5%A4%A7%E5%B1%8F%E9%A1%B9%E7%9B%AE%E5%88%B6%E4%BD%9C%E7%AC%94%E8%AE%B0.html",
      "headers": [
        {
          "level": 3,
          "title": "一、大屏适配方案",
          "slug": "一、大屏适配方案"
        }
      ]
    }
  ],
  "themeConfig": {
    "type": "blog",
    "noFoundPageByTencent": false,
    "nav": [
      {
        "text": "Home",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "博客园",
        "link": "https://www.cnblogs.com/jiajia-hjj/",
        "icon": "reco-blog"
      },
      {
        "text": "GitHub",
        "link": "https://github.com/smallsunnyfox",
        "icon": "reco-github"
      }
    ],
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "logo": "/assets/images/head.jpg",
    "search": true,
    "searchMaxSuggestions": 10,
    "subSidebar": "auto",
    "sidebarDepth": 2,
    "displayAllHeaders": false,
    "sidebar": {
      "/note/ES6/": [
        {
          "title": "ES6",
          "children": [
            "async-await",
            "async函数",
            "BigInt",
            "es6",
            "es6对象",
            "es6箭头函数",
            "es6解构赋值",
            "generator函数",
            "Promise",
            "Promise中的all和race",
            "Promise中的then、catch、finally",
            "Set、Map",
            "Symbol",
            "兼容性",
            "前端模块化",
            "同步和异步"
          ]
        }
      ],
      "/note/bi大屏制作/": [
        {
          "title": "bi大屏制作",
          "children": [
            "大屏项目制作笔记"
          ]
        }
      ],
      "/note/JavaScript/": [
        {
          "title": "JavaScript",
          "children": [
            "call()、apply()、bind()",
            "jquery小笔记",
            "JS中的offsetWidth、offsetHeight、clientWidth、clientHeight等等的详细介绍",
            "js内置对象",
            "js函数",
            "js原型",
            "js字符串",
            "js执行过程",
            "js数据类型",
            "js数据类型2",
            "js数组",
            "js正则",
            "js语句",
            "js闭包",
            "js面向对象",
            "内存泄漏",
            "垃圾回收机制GC",
            "快速排序算法",
            "数组",
            "深拷贝和浅拷贝",
            "编程算法",
            "解决JavaScript数字精度丢失问题的方法",
            "跨域问题",
            "防抖节流"
          ]
        }
      ],
      "/note/VuePress/": [
        {
          "title": "VuePress",
          "children": [
            "vuepress"
          ]
        }
      ],
      "/note/HTML/": [
        {
          "title": "HTML",
          "children": [
            "audio标签常用api",
            "canvas",
            "dpr、设备像素、CSS像素",
            "h5新特性",
            "h5语义化标签",
            "input",
            "meta",
            "script",
            "video",
            "为什么会利用多个域名来存储网站资源更有效？",
            "其他简答题",
            "前端需要注意哪些SEO",
            "图片",
            "如何实现浏览器内多个标签也之间的通信"
          ]
        }
      ],
      "/note/CSS/": [
        {
          "title": "CSS",
          "children": [
            "css 实现上右下左三角",
            "CSS高级常见技巧汇总",
            "DIV水平垂直居中",
            "mixin",
            "retina屏幕1px边框问题",
            "sass",
            "大屏适配方案",
            "字体文件的引用和压缩",
            "渐变",
            "移动端适配方案",
            "设置input",
            "隐藏滚动条或更改滚动条样式"
          ]
        }
      ],
      "/note/": [
        {
          "title": "note",
          "children": []
        }
      ]
    },
    "lastUpdated": "更新时间",
    "author": "HHH",
    "authorAvatar": "/assets/images/head.jpg",
    "startYear": "2022",
    "vssueConfig": {
      "platform": "github-v4",
      "owner": "jiajia-hjj",
      "repo": "blog",
      "clientId": "8c4201a1ee1ae0571196",
      "clientSecret": "212c4a815d147a3ac5bf3cfb34347698e81057da",
      "autoCreateIssue": true
    }
  }
}