/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "CSS": {
      "key": "CSS",
      "scope": "tags",
      "path": "/tag/CSS/",
      "pageKeys": [
        "v-18d957c6",
        "v-61c357fb",
        "v-4c24a392",
        "v-896af054",
        "v-4bd53062",
        "v-39e44bdf",
        "v-4173ef9e",
        "v-2d6dd408",
        "v-7257daa5",
        "v-5a7b5e90",
        "v-5ac3a38d",
        "v-5e1b87bb"
      ]
    },
    "HTML": {
      "key": "HTML",
      "scope": "tags",
      "path": "/tag/HTML/",
      "pageKeys": [
        "v-140730de",
        "v-daeef31a",
        "v-057a5a9c",
        "v-1e565195",
        "v-32967ca5",
        "v-3cdbaef4",
        "v-549cc44e",
        "v-22dbdfb6",
        "v-fbb1ff76",
        "v-61c0020b",
        "v-075cb6cd",
        "v-435a9109",
        "v-4bc1ce98",
        "v-5c4a2edf"
      ]
    },
    "HTML5": {
      "key": "HTML5",
      "scope": "tags",
      "path": "/tag/HTML5/",
      "pageKeys": [
        "v-daeef31a",
        "v-1e565195",
        "v-3cdbaef4",
        "v-fbb1ff76"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "tags",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-27b2f202",
        "v-32c96274",
        "v-a58dcba6",
        "v-9925e42e",
        "v-e313921c",
        "v-c74fcb98",
        "v-35a4858b",
        "v-54cbd2b6",
        "v-7caad962",
        "v-75884935",
        "v-1c4e1118",
        "v-232abf48",
        "v-bd5ec76c",
        "v-21e534be",
        "v-3c54c848",
        "v-19bbd990",
        "v-09689aec",
        "v-b16f5d54",
        "v-3b8007b2",
        "v-5bbaf890",
        "v-06c183ed",
        "v-2c49a5e3",
        "v-18568991"
      ]
    },
    "vuepress": {
      "key": "vuepress",
      "scope": "tags",
      "path": "/tag/vuepress/",
      "pageKeys": [
        "v-bae62ae6"
      ]
    }
  },
  "categories": {
    "CSS": {
      "key": "CSS",
      "scope": "categories",
      "path": "/categories/CSS/",
      "pageKeys": [
        "v-18d957c6",
        "v-61c357fb",
        "v-4c24a392",
        "v-896af054",
        "v-4bd53062",
        "v-39e44bdf",
        "v-4173ef9e",
        "v-2d6dd408",
        "v-7257daa5",
        "v-5a7b5e90",
        "v-5ac3a38d",
        "v-5e1b87bb"
      ]
    },
    "HTML": {
      "key": "HTML",
      "scope": "categories",
      "path": "/categories/HTML/",
      "pageKeys": [
        "v-140730de",
        "v-daeef31a",
        "v-057a5a9c",
        "v-1e565195",
        "v-32967ca5",
        "v-3cdbaef4",
        "v-549cc44e",
        "v-22dbdfb6",
        "v-fbb1ff76",
        "v-61c0020b",
        "v-075cb6cd",
        "v-435a9109",
        "v-4bc1ce98",
        "v-5c4a2edf"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "categories",
      "path": "/categories/JavaScript/",
      "pageKeys": [
        "v-27b2f202",
        "v-32c96274",
        "v-a58dcba6",
        "v-9925e42e",
        "v-e313921c",
        "v-c74fcb98",
        "v-35a4858b",
        "v-54cbd2b6",
        "v-7caad962",
        "v-75884935",
        "v-1c4e1118",
        "v-232abf48",
        "v-bd5ec76c",
        "v-21e534be",
        "v-3c54c848",
        "v-19bbd990",
        "v-09689aec",
        "v-b16f5d54",
        "v-3b8007b2",
        "v-5bbaf890",
        "v-06c183ed",
        "v-2c49a5e3",
        "v-18568991"
      ]
    },
    "vuepress": {
      "key": "vuepress",
      "scope": "categories",
      "path": "/categories/vuepress/",
      "pageKeys": [
        "v-bae62ae6"
      ]
    }
  },
  "timeline": {}
}