/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "CSS": {
      "key": "CSS",
      "scope": "tags",
      "path": "/tag/CSS/",
      "pageKeys": [
        "v-5a7b5e90"
      ]
    }
  },
  "categories": {
    "CSS": {
      "key": "CSS",
      "scope": "categories",
      "path": "/categories/CSS/",
      "pageKeys": [
        "v-5a7b5e90"
      ]
    }
  },
  "timeline": {}
}