/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "CSS",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/CSS/","interval":[0,9]},{"path":"/tag/CSS/page/2/","interval":[10,12]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "HTML",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/HTML/","interval":[0,9]},{"path":"/tag/HTML/page/2/","interval":[10,14]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "HTML5",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/HTML5/","interval":[0,4]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "JavaScript",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/JavaScript/","interval":[0,9]},{"path":"/tag/JavaScript/page/2/","interval":[10,19]},{"path":"/tag/JavaScript/page/3/","interval":[20,23]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "vuepress",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/vuepress/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "CSS",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/CSS/","interval":[0,9]},{"path":"/categories/CSS/page/2/","interval":[10,12]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "HTML",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/HTML/","interval":[0,9]},{"path":"/categories/HTML/page/2/","interval":[10,14]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "JavaScript",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/JavaScript/","interval":[0,9]},{"path":"/categories/JavaScript/page/2/","interval":[10,19]},{"path":"/categories/JavaScript/page/3/","interval":[20,23]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "vuepress",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/vuepress/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]